window.S25Config = {
  sec1: {
    bigTitle: `Super Bright <br class="mb"/> AMOLED <br class="mb"/> Display`,
    watch: `Smart Watch <br class="mb"/> Storm Ultra`,
    titlea: `6.78" AMOLED`,
    desca: `Super Bright <br class="pc"/> Display`,
    titleb: `32MP`,
    descb: `Selfie <br class='pc' /> Camera`,
    titlec: `128GB+12GB*`,
    descc: `(6+6GB) <br class='pc'/> Extended RAM`,
    titled: `6.78"`,
    descd: `Super Bright <br /> AMOLED Display`,
    titlee: `2.02"`,
    desce: `Tested <br class='pc'/> Scratchproof Screen`,
    titlef: `iPulse*`,
    descf: `Werns App <br class='pc'/> Pre-installed on S25 Series`,
  },
  sec2: {
    f1: `Combining cutting-edge technology <br class="mb"/> with <br class="pc"/> avant-garde aesthetic concepts`,
    f2: `Elegance in Excellence`,
    f3: `this is the brand-new S25 <br /> lovingly crafted for the uncompromising you`,
    scale: `1.8`,
  },
  sec3: {
    f1a: `6.78'' Super Bright`,
    f1b: `AMOLED Display`,
    f2a: `Up to`,
    f2b: `12(6+6)GB `,
    f2c: `RAM*`,
    f2d: `+128GB `,
    f2f: `ROM`,
    f2g: `12(6+6)GB RAM*+128GB ROM`,
    f3: `60-month Fluency*`,
    f4a: `32MP`,
    f4b: `AI Selfie Camera`,
    f5a: `7.3mm`,
    f5b: `Ultra Slim Body`,
    f6a: `Infrared `,
    f6b: `Remote Control`,
    f7a: `IP54`,
    f7b: `Dust & Water Resistant`,
    f8a: `Brand New`,
    f8b: `itel OS 14.5`,
    f9a: `Upgradeable to `,
    f9b: `Android 15™`,
  },
  sec4: {
    titlea: `EXCELLENCE IN`,
    titleb: `VISION`,
    desc: `Top-tier display quality, premier brightness,<br class="mb"/> superb eye care, and durability all in one screen. <br /> Countless advantages are embodied in this display.`,
  },
  sec5: {
    title: `A vibrant display <br  class="mb"/> comes to life`,
    desc: `A flagship-level flat screen, featuring cutting-edge luminescent <br class="mb"/> materials, offers amazing brightness, superior display quality,<br /> and eye-care features, performing exceptionally  <br class="mb"/> well in every aspect.`,
    f1a: `120Hz`,
    f1b: `Refresh Rate`,
    f2a: `92%*`,
    f2b: `Screen-to-body Ratio`,
    f3a: `5,000,000: 1`,
    f3b: `Contrast Ratio`,
    f4a: `100%`,
    f4b: `DCI-P3 Color Gamut`,
    f5a: `1.07 Billion`,
    f5b: `Colors`,
    f6a: `1800nits`,
    f6b: `Peak Brightness`,
    f7a: `2160Hz`,
    f7b: `PWM Dimming`,
    f8a: `1500Hz`,
    f8b: `Instant Touch Sampling`,
    f9a: `2436*1080`,
    f9b: `FHD+ Resolution`,
  },
  sec6: {
    title: `Visible in the sunlight`,
    desc: `The global brightness reaches an astonishing 1200 nits,<br class='mb'/> with peak values that are alarmingly high at 1800 nits,<br /> enabling you to vividly perceive the captivating content<br class='mb'/> on the screen even in direct sunlight.*`,
  },
  sec7: {
    titlea: `Wet Touch <br class='pc'/>Display`,
    desca: `Supports wet hands`,
    titleb: `In-Display <br />Fingerprint <br class='pc'/>Unlock`,
    descb: `Fast and safe`,
  },
  sec8: {
    titlea: `EXCELLENCE IN`,
    titleb: `AESTHETICS`,
    desc: `Draw inspiration from magical nature,<br class='mb'/> with the advanced aesthetics and process,<br /> transform the S25 into a trendy item! `,
  },
  sec9: {
    title: `Incredibly slim`,
    desc: `Just 185g & Only 7.3mm*`,
  },
  sec10: {
    titlea: `A stylish creation`,
    desca: `Fashion on one side, technology on the other. By combining<br class='mb'/> natural inspiration with cutting-edge design concepts,<br /> the advanced Optical Coating Process creates two<br class='mb'/> textures of desert and mint, exuding a premium feel.`,
    colora: `Sahara Gleam`,
    infoa: `Inspired by the golden dunes of the Sahara Desert, <br />it's like a magnificent scene of the Sahara shimmering <br class='mb'/> under the sun.`,
    colorb: `Mambo Mint`,
    infob: `Inspired by the popular mint green, fresh and vibrant,<br class='mb'/> combined with the elegance of the mambo <br class='pc'/>dance steps,<br class='mb'/> it's just like the lifestyle of young people who pursue<br class='mb'/> fashion and love life.`,
    titleb: `Black with a twist`,
    descb: `Minimalist design, timeless black, comfortable <br class='mb'/> matte touch, a classic that never fades.`,
    colorc: `Bromo Black`,
    infoc: `Inspired by the basalt of Mount Bromo in Indonesia, <br class='mb'/> it reflects the unique luster <br class='pc'/> of basalt under the sunlight, <br class='mb'/> resembling the shimmering stars in the night sky.`,
  },
  sec11: {
    title: `Sync your mood`,
    desc: `LED Ring Light`,
    info: `The LED ring light not only provides different status <br />information through its lighting effects but also serves <br />as a stylish addition to smartphones, making it <br class='pc'/>visually <br class='mb'/>appealing and practical.`,
    f1: `CHARGING`,
    f2: `NOTIFICATIONS`,
    f3: `GAMING`,
  },
  sec12: {
    title: `A reliable <br />companion`,
    desc: `With an IP54 rating for dust and water resistance, <br />this device is well-protected against everyday wear and tear, <br />including dust ingress and light water splashes.`,
  },
  sec13: {
    titlea: `EXCELLENCE IN`,
    titleb: `PERFORMANCE`,
    desc: `The remarkable performance improvement,<br class='mb'/> coupled with effective software tuning, <br />a "new phone" experience for many years.`,
  },
  sec14: {
    title: `60-month of smooth use`,
    desc: `After undergoing rigorous testing in the itel lab, this phone is <br class='mb'/>  guaranteed to be free of lag for 5 years. <br class='pc'/> thanks to the <br class='mb'/>  powerful Virtual Memory Expansion Tech and Atom <br class='mb'/> Storage Tech, you no longer need to <br class='pc'/>worry about the <br class='mb'/>  phone's performance weakening over time.`,
    f1a: `Up to`,
    f1b: `12(6+6)GB RAM`,
    f1c: `18 Apps running simultaneously.*`,
    f2a: `Up to`,
    f2b: `128GB ROM`,
    f2c: `Capable of storing 30,000+ photos.*`,
  },
  sec15: {
    title: `Unleash the beast`,
    desc: `The S25 features a powerful octa-core processor with ARM <br class='mb'/> Cortex-A75 up to 2.2Ghz, coupled with a Graphite cooling <br class='mb'/> system,<br class='pc'/> to fully unleash its performance and allow you to <br class='mb'/> enjoy mainstream mobile games with ease.`,
  },
  sec16: {
    title: `Super wall-penetrating <br class='mb'/> capability`,
    desc: `The S25 supports Super Wi-Fi, providing ultra-low latency <br class='mb'/> for seamless gaming and automatically switching <br class='pc'/> to <br class='mb'/> the best network across different Wi-Fi networks,<br class='mb'/> offering significantly stronger signal strength in <br class='mb'/> public spaces with shared Wi-Fi.`,
    f1a: `6.5MB/s`,
    f1b: `Download speed when using <br class='mb'/> Wi-Fi and Bluetooth together`,
    f2a: `26ms*`,
    f2b: `Super low latency <br class='mb'/> for gaming`,
    f3a: `5x`,
    f3b: `Faster switch to the <br class='mb'/> optimal Wi-Fi network`,
  },
  sec17: {
    titlea: `The powerhouse in <br class='mb'/> your hand`,
    desca: `The S25 comes with a massive 5000mAh battery and super fast charging of 18W. `,
    titleb: `No gaming compromises`,
    descb: `The phone with Bypass Charging Tech can be powered directly <br class='mb'/> without passing the battery, <br class='pc'/> ensuring a heat-free gaming or <br class='mb'/> watching experience while charging simultaneously.*`,
  },
  sec18: {
    titlea: `EXCELLENCE IN`,
    titleb: `PHOTOGRAPHY`,
    desc: `Ultra-clear front and rear cameras, <br class='mb'/>with specially crafted features and filters, <br /> turning everyone into a photography master.`,
  },
  sec19: {
    f1a: `32MP`,
    f1b: `AI Selfie Camera`,
    f1c: `FOV: 88.9° `,
    f1d: `Aperture: f/2.2`,
    f2a: `50MP`,
    f2b: `Ultra-clear Camera`,
    f2c: `Pixel size: 0.64μm `,
    f2d: `Aperture: f/1.6`,
  },
  sec20: {
    title: `Beauty in focus`,
    desc: `The leading 32MP AI Selfie Camera with large angle, <br /> which features AI Beauty 2.0, captures stunning selfies  <br /> with exceptional detail and clarity, even in group photos.`,
    tipsa: `Support Voice`,
    tipsb: `Control Shutter`,
    tipsc: `Support `,
    tipsd: `Smile Shutter`,
  },
  sec21: {
    title: `Clarity in every detail`,
    subTitlea: `50MP Mode`,
    infoa: `The best-in-class 50MP Ultra Clear Camera allows <br class='pc'/> you to <br class='mb'/> effortlessly capture clear and captivating <br class='pc'/> photos in any <br class='mb'/> complex environment, ranging from <br class='pc'/> low light to backlight <br class='mb'/> scenarios. Even better, <br class='pc'/> you can capture your highlight <br class='mb'/> moments by <br class='pc'/> recording in 2K video!`,
    subTitleb: `Super Night Mode`,
    off: `off`,
    on: `on`,
    hdr: `Super HDR`,
  },
  sec22: {
    title: `Capture with flair`,
    desc: `Dare to integrate AI technology into mobile photography,<br class='mb'/> creating three distinctive stylistic tone filters that allow <br class='mb'/> your <br class='pc'/> photos to effortlessly convey a variety of emotions <br class='mb'/> and atmospheres. Coupled with the use of an exclusive <br /> master watermark, every snapshot you take is instantly <br class='mb'/> transformed into a masterpiece.`,
    f1: `Standard`,
    f2: `Bright`,
    f3: `Master`,
  },
  sec23: {
    title: `Capture with fun`,
    desc: `Embrace the fun of Vlogging with Dual-view Video Recording, <br class='mb'/> effortlessly capturing both your <br class='pc'/> reactions and the stunning <br class='mb'/> scenery you're enjoying, or the engaging <br class='mb'/> interactions with your friends.`,
  },
  sec24: {
    titlea: `EXCELLENCE IN`,
    titleb: `EXPERIENCE`,
    desc: `Every feature is meticulously refined, <br class='mb'/> with continuous updates and optimizations, <br /> ensuring it's always user-friendly.`,
  },
  sec25: {
    title: `Brand New itel OS 14.5`,
    desc: `Based on the latest Android 14, it introduces a more stylish UI <br class='mb'/> design and enhanced desktop widget <br class='pc'/> functionalities, offering <br class='mb'/> you a more aesthetically pleasing and seamless system <br class='mb'/> experience.`,
  },
  sec26: {
    android: {
      title: `Upgradeable to <br class='mb' /> Android 15™`,
      desc: `Support for 2 years of Android system and  <br class='mb'/> security patch <br class='pc'/> upgrades significantly extends <br class='mb'/> the lifespan of your phone.`,
    },
    gpt: {
      title: `GPT AI Assistant`,
      desc: `Say hello to your best <br class='mb'/> assistant! It frees your <br /> hands  and helps you handle <br class='mb'/> many simple tasks.`,
    },
    aiCall: {
      title: `AI Call Noise <br class='pc'/>Cancellation`,
    },
    aiWallpaper: {
      title: `AI Wallpaper`,
    },
    askAi: {
      title: `ASK AI`,
    },
    dynamicBar: {
      title: `Dynamic Bar`,
      desc: `Welcome to the Dynamic Bar, where accessing <br class='mb'/> important notifications <br class='pc'/> is now more <br class='mb'/> convenient and seamless than ever before.`,
    },
    aod: {
      title: `Smart AOD`,
      desc: `Important information <br class='mb'/> is easily accessible.`,
    },
    infrared: {
      title: `Infrared <br class='mb'/> Remote Control`,
      desc: `Turn your smartphone into <br class='mb'/> a versatile <br class='pc'/> controller for <br class='mb'/> home appliances.*`,
    },
    nfc: {
      title: `NFC`,
      desc: `There is no need to <br class='mb'/> bring a wallet or <br class='pc'/> a <br class='mb'/> transport card when <br class='mb'/> going out.*`,
    },
    dts: {
      title: `Sound By DTS`,
      desc: `DTS audio brings <br class='mb'/> immersive, <br class='pc'/> high-fidelity <br class='mb'/> sound to your <br class='pc'/> smartphone <br class='mb'/> for an enhanced <br class='pc'/> listening <br class='mb'/> experience.`,
    },
  },
  sec27: {
    title: `Smart  <br class='pc'/> connectivity`,
    desc: `It is built-in with the iPulse App and supports seamless <br /> interconnection with your itel watch, allowing you to <br class='pc'/> remotely <br class='mb'/> control smartphone photography and synchronize <br class='pc'/> health <br class='mb'/> data to the phone. It's not just about the Internet of <br /> Things, it represents a trendy lifestyle.*`,
  },
  sec28: {
    notes: `Notes`,
    f1: `1. The 60-month Fluency data is obtained from the itel Lab. Actual data may <br class='mb'/>  vary due to factors such as test environments or calculation methods, <br class='pc'/> so please <br class='mb'/>  refer to the actual product.`,
    f2: `2. S25 128+12GB version's RAM is composed of (6+6)GB expansion.`,
    f3: `3. The screen-to-body ratio and brightness data are obtained from the itel Lab. <br class='mb'/> Actual data may vary due to factors such as test environments or <br class='pc'/> calculation <br class='mb'/> methods, so please refer to the actual product.`,
    f4: `4. The weight and thickness data are obtained from the itel Lab. Actual data <br class='mb'/> may vary due to factors such as test environments or calculation  <br class='pc'/> methods, <br class='mb'/> so please refer to the actual product.`,
    f5: `5. The storage data of "30,000+ Photos" is obtained from the itel Lab. Actual <br class='mb'/> data may vary due to factors such as test environments or <br class='pc'/> calculation methods, <br class='mb'/> so please refer to the actual product.`,
    f6: `6. The 18 Apps Running Simultaneously data is obtained from the itel Lab.<br class='mb'/ Actual data may vary due to factors such as test environments or <br class='pc'/> calculation <br class='mb'/ methods, so please refer to the actual product.`,
    f7: `7. The data of Super Wi-Fi is obtained from the itel Lab. Actual data may vary <br class='mb'/> due to factors such as test environments or calculation methods, so <br class='pc'/> please refer <br class='mb'/> to the actual product. `,
    f8: `8. The battery of itel S25 has a typical capacity of 5000mAh and a rated <br class='mb'/> capacity of 4900mAh.`,
    f9: `9. The data of 1000 charge cycles is obtained from the itel Lab. Actual data may vary due to factors such as test environments or calculation <br class='pc'/> methods, so please refer to the actual product.`,
    f10: `9. The data of Bypass Charging Tech is obtained from the itel Lab. Actual data <br class='mb'/> may vary due to factors such as test environments or calculation <br class='pc'/> methods, so <br class='mb'/> please refer to the actual product.`,
    f11: `10. Android is a trademark of Google LLC.`,
    f12: `11. The availability of Infrared Remote Control and NFC features may vary by <br class='mb'/> region and device. Please refer to the actual situation for details.`,
    f13: `12. iPulse, itel's own watch app, is widely compatible and pre-installed on itel <br class='mb'/> S25 Series.`,
    f14: `13. Product images are for reference only, please refer to the actual product. <br class='mb'/> Some specifications and descriptions may change due to supplier <br class='pc'/> replacements, <br class='mb'/> please refer to the actual product. The data mentioned is based on our design <br class='mb'/> technical specifications, lab, and supplier test data, <br class='pc'/> and actual situations may <br class='mb'/> vary slightly due to different testing software versions, specific testing <br class='mb'/> environments, and versions.`,
  },
  video: {
    sec23: {
      pc: {
        src: "/fileadmin/assets/v/S25/dist/videos/sec23Pc.mp4",
        post: "",
      },
      mob: {
        src: "/fileadmin/assets/v/S25/dist/videos/sec23Pc.mp4",
        post: "",
      },
    },
    sec2: {
      pc: {
        src: "/fileadmin/assets/v/S25/dist/videos/shortPc.mp4",
        post: "",
      },
      mob: {
        src: "/fileadmin/assets/v/S25/dist/videos/shortMb.mp4",
        post: "",
      },
    },
    fullVideo: {
      pc: {
        src: "/fileadmin/assets/v/S25/dist/videos/longPc.mp4",
        post: "",
      },
      mob: {
        src: "/fileadmin/assets/v/S25/dist/videos/longMb.mp4",
        post: "",
      },
    },
  },
}
