// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore

window.pop8Config = {
  sec1: {
    title: "All You Want Just Doubled",
    p1: "Double <br/> Speakers",
    p2: "Double <br/> Rear Camera",
    p3: "Double <br/> RAM <span>Up to <br/> 4+4GB</span>",
    p4: "Double <br/> Interactive Way",
    tips: "64GB ROM+6GB RAM*(3GB+3GB Extended); 64GB ROM+8GB RAM*(4GB+4GB Extended) <br/> 128GB ROM+8GB RAM*(4GB+4GB Extended)",
    icon1Top: "1%",
    icon1Left: "-1%",
    icon2Top: "1%",
    icon2Left: "83%",
    icon3Top: "46%",
    icon3Left: "-2%",
    icon4Top: "52%",
    icon4Left: "28%",
    icon5Top: "41%",
    icon5Left: "85%",
  },
  sec3: {
    text: "Aesthetics",
    title: "Dual Textures, <br/> Next-level <br/> Allure",
    icon1Top: "-7%",
    icon1Left: "-9%",
    icon2Top: "32%",
    icon2Left: "57%",
    icon3Top: "67%",
    icon3Left: "26%",
    t1: "Minimalist Square Shape",
    d1: "Prep for a posh texture and design overhaul! The slim body comes in two styles: Rainbow Ring for a pop of color burst; And Magic Skin 2.0 for a luxury sensation that feels like premium leather - crafted from 100% hazard-free high-polymer silicone! Pick your look and feel. Level up your style!",
    param1t: "8.55mm",
    param1d: "Ultra Slim",
    param2t: "Sparkle Sand",
    param2d: "New Generation",
    param3t: "Million Colour",
    param3d: "Coating",
    tips: '*Evidenced by data from TRANSSION LAB',
  },
  sec4: {
    title: 'Sail Seamlessly in a Wider Wonderland.',
    icon1Top: '-18%',
    icon1Left: '-16%',
    icon2Top: '-29%',
    icon2Left: '36%',
    icon3Top: '17%',
    icon3Left: '89%',
    icon4Top: '69%',
    icon4Left: '-15%',
    t1: `6.6'' 90Hz Hole Screen`,
    d1: `Explore a vast wonderland on a 6.6-inch ultra-wide display! At a whopping 90.5% screen-to-body ratio - a rarity in its class, feel like floating on a boundless sea of visual feast! It's a seamless adventure, as 90Hz high-refresh rate guarantees ultra-responsive interactions!
    Surprises await between each tap.`,
    param1t: `6.6'' Hole`,
    param1d: 'Large Screen',
    param2t: '90Hz',
    param2d: 'Refresh Rates',
    param3t: '8H',
    param3d: 'Surface Hardness',
    tips: '*Evidenced by data from TRANSSION LAB',
  },
  sec5: {
    title: 'Beauty + Utility <br/> Best of Both Worlds',
    icon1Top: '-35%',
    icon1Left: '-13%',
    icon2Top: '-53%',
    icon2Left: '56%',
    icon3Top: '74%',
    icon3Left: '24%',
    icon4Top: '69%',
    icon4Left: '69%',
    t1: 'Self-developed Dynamic Port',
    d1: `Welcome aboard TECNO's ingenious Dynamic Port, seamlessly integrated into the screen display. Intuitive UI brings efficient notifications - Stay in the know without frequent unlocking, checking, or app switching. Traditional mode is also available for your flexibility.
    Experience simplified, but not compromised!`,
  },
  sec6: {
    text: 'Image',
    title: 'Front + Back <br/> Clarity on Both <br/> Ends',
    icon1Top: '55%',
    icon1Left: '-14%',
    icon2Top: '-26%',
    icon2Left: '26%',
    icon3Top: '55%',
    icon3Left: '28%',
    icon4Top: '8%',
    icon4Left: '61%',
    t1: '8MP Dual Flash Selfie',
    d1: 'Dusk to dawn, in or out, selfie master on the front is always here to deliver! 8MP camera for sharp clarity, with light-sensitive pixel, dual flash ,and screen fill light for your radiant glow. Plus battle-tested beauty enhancements for every skin tone! Step into the spotlight and let your inner star be doubly shine.',
    param1t: 'Super Night',
    param1d: 'Algorithm',
    param2t: '8MP',
    param2d: 'Ultra Clear Selfie',
    param3t: '1.12um',
    param3d: 'Ultra Large Pixel Unit',
    param4t: 'Dual Flash Light',
    param4d: 'Natural Lighting',
    tips: '*Pictures are for illustration only, please refer to the actual product form.',
  },
  sec7: {
    t1: '13MP HDR Portrait Camera',
    d1: 'Super-Wide aperture + Super-Large pixel unit. <br/> Let the SUPER DUO on the back supercharge your portraits in all lighting. Undimmed even in the backlight! HDR merges frames for clarity to outshine, while background blur crafts a stage for you to star. <br/> Capture beauty, whenever, wherever.',
    param1t: '13MP',
    param1d: 'Ultra Clear',
    param2t: 'HDR Effect',
    param2d: 'Multi-frame Fusion',
    param3t: 'F 1.8',
    param3d: 'Large Aperture',
    param4t: '1.12um',
    param4d: 'Ultra Large Pixel Unit',
    tips: '*Pictures are for illustration only, please refer to the actual product form.',
  },
  sec8: {
    title: 'Eyes on You!',
    icon1Top: '-21%',
    icon1Left: '-8%',
    icon2Top: '-41%',
    icon2Left: '23%',
    icon3Top: '-21%',
    icon3Left: '56%',
    t1: 'AR Shot',
    d1: 'Express your vibrant self with playful cartoon avatars, lively backgrounds, and a variety of AR elements. <br/> Stand out and steal the show!',
    tips: '*Videos are for illustration only, please refer to the actual product form.',
  },
  sec9: {
    title: "Quality",
  },
  sec10: {
    bigTitle: `Double Beat, Over <br />Double the Treat!`,
    icon1: {
      top: "-50%",
      left: "-13%",
    },
    icon2: {
      top: "-57%",
      left: "58%",
    },
    icon3: {
      top: "74%",
      left: "-8%",
    },
    icon4: {
      top: "-9%",
      left: "86%",
    },

    title: `Stereo Dual Speakers <br /> with DTS LISTEN`,
    desc: `Up your mobile audio experience to theatre-level with dual speakers! Savoring music or watching videos, it feels like being surrounded by a live performance, with sprites of melodies coming to life around you.`,
    p1a: `Stereo Dual <br /> Speakers`,
    p1b: `Loudness Enhancement`,
    p2a: `Audio <br />Booster`,
    p2b: `Calling Assistant`,
    tips: `*Pictures are for illustration only, please refer to the actual product form.`,
  },
  sec11: {
    bigTitle: `No Trouble,<br /> Just Double!`,
    icon1: {
      top: "-30%",
      left: "-9.8%",
    },
    icon2: {
      top: "-31%",
      left: "47%",
    },
    icon3: {
      top: "41%",
      left: "54%",
    },

    title: `Large Storage with <br /> System Slimming`,
    desc: `No more tradeoff! With spacious memory, keep all your loved music and cherished photos. Up to 4GB extended memory enhances seamless operations, with System Slimming to keep it clean and clutter-free.<br /> Leave lag behind. Keep only speed, smoothness, and stability.`,
    p1a: `Up to 1TB`,
    p1b: `Extended Storage`,
    p2a: `Up to 8GB`,
    p2b: `Fusion Memory`,
    p3a: `System Slimming`,
    p3b: `Deep Cleanup`,
    tips: `*Double RAM（Up to 8GB, 4GB+4GB Extended RAM）<br />
    *The 1TB extended storage is only available on models with a 1TB MicroSD card. Actual storage available may vary depending on pre-installed software.<br />
    *MicroSD card must be purchased separately and is not included in this product.<br />
    *Pictures are for illustration only, please refer to the actual product form.`,
  },
  sec12: {
    bigTitle: `Double Down <br /> On Power!`,
    icon1: {
      top: "48%",
      left: "-12.5%",
    },
    icon2: {
      top: "-35%",
      left: "27%",
    },
    icon3: {
      top: "7%",
      left: "63%",
    },

    title: `5000mAh <br /> Large Battery <br /> with Type-C`,
    desc: `Say goodbye to power anxiety with a mega, marathon battery! Dive into non-stop videos and music. The versatile Type-C port plays along – up or down, plug it in any way you want. A feature usually reserved for pricier models - level up your experience, level down your costs!`,
    p1a: `5000mAh`,
    p1b: `Large Battery`,
    p2a: `10W`,
    p2b: `Charge`,
    p3a: `Type-C`,
    p3b: `Interface`,
    tips: `*Pictures are for illustration only, please refer to the actual product form.`,
  },
  sec13: {
    bigTitle: `Half the Effort,<br />Tip Awake a Smart<br /> World`,
    icon1: {
      top: "-15%",
      left: "-14%",
    },
    icon2: {
      top: "-3%",
      left: "85%",
    },
    icon3: {
      top: "64%",
      left: "26%",
    },

    title: `Side Edge Fingerprint Unlocking`,
    desc: `Leading the range with leading-edge side-mounted fingerprint sensor. Unlock intuitively, and elegantly. No lifting or fumbling. A gentle touch with fingertip - Voila, your device is ready at your service.`,
    p1a: `Millisecond Grade`,
    p1b: `Unlocking Speed`,
    p2a: `About 10m㎡`,
    p2b: `Large Sensor Area`,
    tips: `*Evidenced by data from TRANSSION LAB`,
  },
  sec14: {
    bigTitle: `Race for<br /> Milliseconds, on<br /> Duo Drive.`,
    icon1: {
      top: "0%",
      left: "-12.5%",
    },
    icon2: {
      top: "-17%",
      left: "40.5%",
    },
    icon3: {
      top: "36%",
      left: "71%",
    },

    title: `Octa-core Processor`,
    desc: `Powered by octa-core Arm Cortex-A53 processor, offering up to 2.2GHz peak frequency for lightning-fast mobile experience! While the self-developed Darwin Engine keeps your device cool so you chill in longer usage.<br /> Enjoy uninterrupted, silky-smooth performance without a hitch!`,
    p1a: `2.2GHz`,
    p1b: `Peak Frequency`,
    p2a: `Octa-core Arm Cortex-A53`,
    p2b: `Processor`,
    tips: `*Pictures are for illustration only, please refer to the actual product form.`,
  },
}
