// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore

window.pop8Config = {
  sec1: {
    title: `All You Want Just Doubled`,
    p1: "Double <span></span> <br/> Speakers",
    p2: "6.6'' 90Hz <br/> Hole Screen",
    p3: "Up to <span>4+4 GB <br/> Extended RAM</span><br/> 128GB+8GB* ",
    p4: "5000mAh <br/> with Type-C",
    tips: "64GB ROM+6GB RAM*(3GB+3GB Extended); <br/> 64GB ROM+8GB RAM*(4GB+4GB Extended) <br/> 128GB ROM+8GB RAM*(4GB+4GB Extended)",
    icon1Top: "52%",
    icon1Left: "88%",
    icon1MobTop: "52%",
    icon1MobLeft: "83%",
  },
  sec2: {
    t1: "6.6'' 90Hz Hole Screen <br/> Self-developed Dynamic Port",
    t2: "Minimalist <br/> Square <br/> Shape",
    t3: "Large Storage <span>1TB</span> Extended SD Card",
    t4: "5000mAh with Type-C ",
    t5: "Side Edge Fingerprint Unlocking ",
    t6: "Stereo Dual Speakers with DTS LISTEN ",
    t7: "Camera",
  },
  sec3: {
    text: "Aesthetics",
    title: "Dual Textures, <br/> Next-level <br/> Allure",
    icon1Top: "-7%",
    icon1Left: "-8%",
    icon2Top: "29%",
    icon2Left: "53%",
    icon3Top: "67%",
    icon3Left: "23.6%",
    icon1MobTop: "-7%",
    icon1MobLeft: "-16%",
    icon2MobTop: "29%",
    icon2MobLeft: "85%",
    icon3MobTop: "67%",
    icon3MobLeft: "37.6%",
    t1: "Minimalist Square Shape",
    d1: "Prep for a posh texture and design overhaul! The slim body comes in<br /> two styles: Rainbow Ring for a pop of color burst; And Magic Skin 2.0<br /> for a luxury sensation that feels like premium leather - crafted from 100%<br /> hazard-free high-polymer silicone!<br /> Pick your look and feel. Level up your style!",
    param1t: "8.55mm",
    param1d: "Ultra Slim",
    param2t: "Sparkle Sand",
    param2d: "New Generation",
    param3t: "Million Colour",
    param3d: "Coating",
    param4t: "8.75mm",
    param4d: "Ultra Slim",
    param5t: `Magic<br /> Skin 2.0`,
    param5d: "Leather",
    param6t: `100%<br /> Recyclable`,
    param6d: `Back Cover`,
    param7t: `Zero`,
    param7d: `Harmful<br /> Substance`,
    tips: "*Evidenced by data from TRANSSION LAB",
  },
  sec4: {
    title: "Sail Seamlessly in a Wider Wonderland.",
    icon1Top: "-18%",
    icon1Left: "-16%",
    icon2Top: "-29%",
    icon2Left: "36%",
    icon3Top: "17%",
    icon3Left: "92%",
    icon4Top: "69%",
    icon4Left: "-15%",
    icon3MobTop: "5%",
    icon3MobLeft: "85%",
    t1: `6.6'' 90Hz Hole Screen`,
    d1: `Explore a vast wonderland on a 6.6-inch<br /> ultra-wide display! At a whopping 90.5% <br />screen-to-body ratio - a rarity in its class,<br /> feel like floating on a boundless sea of<br /> visual feast! It's a seamless adventure, as <br />90Hz high-refresh rate guarantees ultra-<br />responsive interactions! <br />Surprises await between each tap.`,
    param1t: `6.6'' Hole`,
    param1d: "Large Screen",
    param2t: "90Hz",
    param2d: "Refresh Rates",
    param3t: "8H",
    param3d: "Surface Hardness",
    tips: "*Evidenced by data from TRANSSION LAB",
  },
  sec5: {
    title: "Beauty + Utility <br/> Best of Both Worlds",
    icon1Top: "14%",
    icon1Left: "-12%",
    icon2Top: "-53%",
    icon2Left: "65%",
    icon3Top: "74%",
    icon3Left: "28.5%",
    icon4Top: "69%",
    icon4Left: "80%",
    icon1MobTop: "-23%",
    icon1MobLeft: "-21%",
    icon2MobTop: "-28%",
    icon2MobLeft: "89%",
    icon3MobTop: "59%",
    icon3MobLeft: "38%",
    icon4MobTop: "33%",
    icon4MobLeft: "70%",
    t1: "Self-developed Dynamic Port",
    d1: `Welcome aboard TECNO's ingenious Dynamic Port,<br class='pc'/> seamlessly integrated into the screen display. Intuitive UI<br class='pc'/> brings efficient notifications - Stay in the know without<br class='pc'/> frequent unlocking, checking, or app switching. Traditional<br class='pc'/> mode is also available for your flexibility.<br /> Experience simplified, but not compromised!`,
  },
  sec6: {
    text: "Image",
    title: "Front + Back <br/> Clarity on Both <br/> Ends",
    icon1Top: "55%",
    icon1Left: "-13.7%",
    icon2Top: "-26%",
    icon2Left: "26%",
    icon3Top: "55%",
    icon3Left: "28%",
    icon4Top: "-2%",
    icon4Left: "62%",
    icon1MobTop: "55%",
    icon1MobLeft: "-13.7%",
    icon2MobTop: "-26%",
    icon2MobLeft: "26%",
    icon3MobTop: "55%",
    icon3MobLeft: "28%",
    icon4MobTop: "-14%",
    icon4MobLeft: "85%",
    t1: "8MP Dual Flash Selfie",
    d1: "Dusk to dawn, in or out, selfie master on the front is always<br class='pc'/> here to deliver! 8MP camera for sharp clarity, with light-sensitive<br class='pc'/> pixel, dual flash ,and screen fill light for your radiant glow. Plus<br class='pc'/> battle-tested beauty enhancements for every skin tone!<br class='pc'/> Step into the spotlight and let your inner star be doubly shine.",
    param1t: "Super Night",
    param1d: "Algorithm",
    param2t: "8MP",
    param2d: "Ultra Clear Selfie",
    param3t: "1.12μm",
    param3d: "Ultra Large Pixel Unit",
    param4t: "Dual Flash Light",
    param4d: "Natural Lighting",
    tips: "*Pictures are for illustration only, please refer to the actual product form.",
  },
  sec7: {
    t1: "13MP HDR Portrait Camera",
    d1: "Super-Wide aperture + Super-Large pixel unit. <br/> Let the SUPER DUO on the back supercharge your portraits in all lighting.<br class='pc'/> Undimmed even in the backlight! HDR merges frames for clarity to outshine,<br /> while background blur crafts a stage for you to star. <br/> Capture beauty, whenever, wherever.",
    param1t: "13MP",
    param1d: "Ultra Clear",
    param2t: "HDR Effect",
    param2d: "Multi-frame Fusion",
    param3t: "F 1.8",
    param3d: "Large Aperture",
    param4t: "1.12μm",
    param4d: "Ultra Large Pixel Unit",
    tips: "*Pictures are for illustration only, please refer to the actual product form.",
  },
  sec8: {
    title: "Eyes on You!",
    icon1Top: "-21%",
    icon1Left: "-8%",
    icon2Top: "-41%",
    icon2Left: "23%",
    icon3Top: "2%",
    icon3Left: "-8%",
    icon1MobTop: "-21%",
    icon1MobLeft: "-12%",
    icon2MobTop: "-41%",
    icon2MobLeft: "34%",
    icon3MobTop: "-21%",
    icon3MobLeft: "-21%",
    t1: "AR Shot",
    d1: "Express your vibrant self with playful cartoon avatars,<br class='mob'/> lively backgrounds, and a variety of AR elements. <br/> Stand out and steal the show!",
    tips: "*Videos are for illustration only, please refer to the actual product form.",
  },
  sec9: {
    title: "Performance",
  },
  sec10: {
    bigTitle: `Double Beat, Over <br class='pc'/>Double the Treat!`,
    icon1: {
      top: "-26%",
      left: "-9%",
      mobtop: "-34%",
      mobleft: "3%",
    },
    icon2: {
      top: "-57%",
      left: "58%",
      mobtop: "-36%",
      mobleft: "68%",
    },
    icon3: {
      top: "74%",
      left: "-8%",
      mobtop: "49%",
      mobleft: "7%",
    },
    icon4: {
      top: "-9%",
      left: "86%",
      mobtop: "-2%",
      mobleft: "83%",
    },

    title: `Stereo Dual Speakers <br class='pc'/> with DTS LISTEN`,
    desc: `Up your mobile audio experience to theatre-level with dual<br /> speakers! Savoring music or watching videos, it feels like being<br />  surrounded by a live performance, with sprites of melodies<br />  coming to life around you.`,
    p1a: `Stereo Dual <br /> Speakers`,
    p1b: `Loudness Enhancement`,
    p2a: `Audio <br />Booster`,
    p2b: `Calling Assistant`,
    tips: `*Pictures are for illustration only, please refer to the actual product form.`,
  },
  sec11: {
    bigTitle: `No Trouble,<br /> Just Double!`,
    icon1: {
      top: "-30%",
      left: "-9.8%",
      mobtop: "-30%",
      mobleft: "4%",
    },
    icon2: {
      top: "-31%",
      left: "47%",
      mobtop: "-35%",
      mobleft: "57%",
    },
    icon3: {
      top: "56%",
      left: "57%",
      mobtop: "41%",
      mobleft: "64%",
    },

    title: `Large Storage with <br class='pc'/> System Slimming`,
    desc: `No more tradeoff! With spacious memory, keep all your loved music and cherished photos. Up to 4GB extended memory enhances seamless operations, with System Slimming to keep it clean and clutter-free.<br /> Leave lag behind. Keep only speed, smoothness, and stability.`,
    p1a: `Up to 1TB`,
    p1b: `Extended Storage`,
    p2a: `Up to 8GB`,
    p2b: `Fusion Memory`,
    p3a: `System Slimming`,
    p3b: `Deep Cleanup`,
    tips: `*Double RAM（Up to 8GB, 4GB+4GB Extended RAM）<br />
    *The 1TB extended storage is only available on models with a 1TB MicroSD card. Actual storage available may vary depending on pre-installed software.<br />
    *MicroSD card must be purchased separately and is not included in this product.<br />
    *Pictures are for illustration only, please refer to the actual product form.`,
  },
  sec12: {
    bigTitle: `Double Down <br /> On Power!`,
    icon1: {
      top: "51%",
      left: "62%",
      mobtop: "56%",
      mobleft: "67%",
    },
    icon2: {
      top: "-35%",
      left: "27%",
      mobtop: "-55%",
      mobleft: "38%",
    },
    icon3: {
      top: "7%",
      left: "63%",
      mobtop: "-1%",
      mobleft: "72%",
    },

    title: `5000mAh <br class='pc'/> Large Battery <br class='pc'/> with Type-C`,
    desc: `Say goodbye to power anxiety with a mega,<br class='pc'/> marathon battery! Dive into non-stop videos<br class='pc'/> and music. The versatile Type-C port plays<br class='pc'/> along – up or down, plug it in any way you<br class='pc'/> want. A feature usually reserved for pricier<br class='pc'/> models - level up your experience, level down<br class='pc'/> your costs!`,
    p1a: `5000mAh`,
    p1b: `Large Battery`,
    p2a: `10W`,
    p2b: `Charge`,
    p3a: `Type-C`,
    p3b: `Interface`,
    tips: `*Pictures are for illustration only, please refer to the actual product form.`,
  },
  sec13: {
    bigTitle: `Half the Effort,<br />Tip Awake a Smart<br /> World`,
    icon1: {
      top: "-15%",
      left: "-14%",
      mobtop: "-15%",
      mobleft: "1%",
    },
    icon2: {
      top: "-3%",
      left: "85%",
      mobtop: "-8%",
      mobleft: "82%",
    },
    icon3: {
      top: "-2%",
      left: "-12%",
      mobtop: "-9%",
      mobleft: "1%",
    },

    title: `Side Edge Fingerprint Unlocking`,
    desc: `Leading the range with leading-edge side-mounted fingerprint<br class='pc'/> sensor. Unlock intuitively, and elegantly. No lifting or fumbling.<br class='pc'/> A gentle touch with fingertip - Voila, your device is ready at<br class='pc'/> your service.`,
    p1a: `Millisecond Grade`,
    p1b: `Unlocking Speed`,
    p2a: `About 10mm²`,
    p2b: `Large Sensor Area`,
    tips: `*Evidenced by data from TRANSSION LAB`,
  },
  sec14: {
    bigTitle: `Race for<br /> Milliseconds, on<br /> Duo Drive.`,
    icon1: {
      top: "0%",
      left: "-15%",
      mobtop: "-9%",
      mobleft: "4%",
    },
    icon2: {
      top: "-17%",
      left: "40.5%",
      mobtop: "-17%",
      mobleft: "51.5%",
    },
    icon3: {
      top: "35%",
      left: "70%",
      mobtop: "35%",
      mobleft: "80%",
    },

    title: `Octa-core Processor`,
    desc: `Powered by octa-core Arm<br /> Cortex-A53 processor, offering up<br /> to 2.2GHz peak frequency for<br /> lightning-fast mobile experience!<br /> While the self-developed Darwin<br /> Engine keeps your device cool so<br /> you chill in longer usage.<br /> Enjoy uninterrupted, silky-smoothn<br /> performance without a hitch!`,
    p1a: `2.2GHz`,
    p1b: `Peak Frequency`,
    p2a: `Octa-core Arm Cortex-A53`,
    p2b: `Processor`,
    tips: `*Pictures are for illustration only, please refer to the actual product form.`,
  },
  sec6Video: {
    // pc: "http://localhost:5173/src/assets/video/sec6Pc.mp4",
    // v1Post: "",
    pc: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/video/sec6Pc.mp4",
    v1Post: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/webp/sec6PcPoster.jpg",
  },
  sec7Video: {
    // pc: "http://localhost:5173/src/assets/video/sec7Pc.mp4",
    // mob: "http://localhost:5173/src/assets/video/sec7Mob.mp4",
    // v1Post: "",
    pc: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/video/sec7Pc.mp4",
    mob: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/video/sec7Mob.mp4",
    v1Post: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/webp/sec7PcPoster.jpg",
    v1PostMob: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/webp/sec7MobPoster.jpg",
  },
  sec8Video: {
    // 本地
    // v1: "http://localhost:5173/src/assets/video/sec8V1.mp4",
    // v1Post: "",
    // v2: "http://localhost:5173/src/assets/video/sec8V2.mp4",
    // v2Post: "",
    // v3: "http://localhost:5173/src/assets/video/sec8V3.mp4",
    // v3Post: "",
    // v4: "http://localhost:5173/src/assets/video/sec8V4.mp4",
    // v4Post: "",
    // v5: "http://localhost:5173/src/assets/video/sec8V5.mp4",
    // v5Post: "",
    // v6: "http://localhost:5173/src/assets/video/sec8V6.mp4",
    // v6Post: "",

    // 线上
    v1: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/video/sec8V1.mp4",
    v1Post: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/webp/sec8V1Poster.jpg",
    v2: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/video/sec8V2.mp4",
    v2Post: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/webp/sec8V2Poster.jpg",
    v3: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/video/sec8V3.mp4",
    v3Post: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/webp/sec8V3Poster.jpg",
    v4: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/video/sec8V4.mp4",
    v4Post: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/webp/sec8V4Poster.jpg",
    v5: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/video/sec8V5.mp4",
    v5Post: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/webp/sec8V5Poster.jpg",
    v6: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/video/sec8V6.mp4",
    v6Post: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/webp/sec8V6Poster.jpg",
  },
  sec10Video: {
    // pc: "http://localhost:5173/src/assets/video/sec10Pc.mp4",
    // mob: "http://localhost:5173/src/assets/video/sec10Mob.mp4",
    pc: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/video/sec10Pc.mp4",
    mob: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/video/sec10Mob.mp4",
    v1Post: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/webp/sec10PcPoster.jpg",
    v1PostMob: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/webp/sec10MobPoster.jpg",
  },
  sec11Video: {
    // pc: "http://localhost:5173/src/assets/video/sec11Pc.mp4",
    pc: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/video/sec11Pc.mp4",
    v1Post: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/webp/sec11PcPoster.jpg",
  },
  sec12Video: {
    // pc: "http://localhost:5173/src/assets/video/sec12Pc.mp4",
    // mob: "http://localhost:5173/src/assets/video/sec12Mob.mp4",
    pc: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/video/sec12Pc.mp4",
    mob: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/video/sec12Mob.mp4",
    v1Post: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/webp/sec12PcPoster.jpg",
    v1PostMob: "https://www.tecno.mez100.com.cn/fileadmin/sitedesign/product/pop-8/dist/webp/sec12MobPoster.jpg",
  },
}
