// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
window.pova5ProConfig = {
  sec1: {
    p1: "MediaTek <span>D60805G</span> <br /> Processor",
    p2: "<span>5000mAh</span> <br />Mega Battery",
    p3: "<span>68W</span>Ultra <br />Charge",
    p4: "<span>256GB</span> <br />ROM",
    p5: "<span>8GB</span> <br /> RAM",
    p1m: " MediaTek D6080 5G Processor",
    p2m: "5000mAh Mega Battery",
    p3m: "68W Ultra Charge",
    p4m: "256GB ROM + 8GB RAM",
    useImage: false,
    pcImgSrc: "",
    mobImgSrc: "",
  },
  sec3: {
    p1: "Innovative <br />Design",
    p2: "Stunning <br />Power",
    p3: "Ultimate <br />Performance",
    p4: "High-Definition <br />Camera",
    p5: "HIOS13",
  },
  sec4: {
    title: "NEW DESIGN, NEW <br /> REVOLUTION",
  },
  sec5: {
    title: "Shine Brighter, Look Cooler",
    sub: "Turbo Light Mecha Design",
    desc: `POVA 5 PRO features an innovative LED light strip <br /> and 9-color RGB interactive design. With every flash, <br class="pc"/> you<br class="mob"/> become the center of attention.`,
    text1: "Lifelike 3D Mecha Design with Turbo Stripes",
    text2: "NCVM Process",
  },
  sec6: {
    p1: `Dark <br class="pc"/>Illusion`,
    p2: `Silver <br class="pc"/>Fantasy`,
  },
  sec7: {
    title: "Dominate with <br /> Unstoppable Power!",
  },
  sec8: {
    titlea: "5000mAh Mega Battery",
    suba: "Enjoy A Full-day Gaming Thrill",
    desca: `Work or entertainment, 5000mAh is  <br class="pc"/>sufficient to support <br  class="mob"/>any daily use  <br  class="pc"/>throughout an entire day. No need  <br  class="pc"/>to<br  class="mob"/> worry about running out of <br  class="pc"/>power anymore!`,
    p1a: "31H+",
    p1b: "Continuous <br />Calling",
    p2a: "9H+",
    p2b: "Uninterrupted <br />Gaming",
    p3a: "13H+",
    p3b: "Browse <br />Surfing",
    p4a: "12H+",
    p4b: "Video <br />Screening",
    titleb: "STS Secure Battery Technology",
    subb: "The Power You Can Trust",
    descb:
      "The STS coating technology ensures safety by preventing dangerous internal short circuits caused by direct contact between aluminum foil and anode, providing you with complete peace of mind.",
    titlec: "68W Ultra Charge",
    subc: "45 Minutes,Chargeing for 100%",
    descc: `Charge your phone in a flash - 50% <br class="pc"/>in 15 mins, fully<br class="mob"/> charge in 45 min`,
    p5a: "50% +",
    p5b: "charged in 15 min",
    p6a: "10W",
    p6b: "Reverse Charging",
  },
  sec9: {
    title: "Ultimate Performance. <br />Immensed Gratification",
  },
  sec10: {
    title: "MediaTek Dimensity 6080 5G Processor",
    sub: "Join the 5G League, Take One Step Ahead",
    desc: `Equipped with MediaTek Dimensity 6080 5G high-speed<br /> chip, Get lightning-fast performance for an extraordinary<br />experience.`,
    p1a: "6nm",
    p1b: "Architecture",
    p2a: "3.0 Lite",
    p2b: "HyperEngine",
    p3a: "CPU",
    p3b: "Octa-Core",
  },
  sec11: {
    titlea: `8+8GB Extended<br class="mob"/> RAM`,
    desca:
      "Extraordinarily Smooth Experience <br />Say Goodbye to Latency, Slow Loading",
    p1a: "67%",
    p1b: `Hot Start-up`,
    p2a: "25",
    p2b: "Background Cached",
    p3a: "39%",
    p3b: "Avg App Start-up time",
    titleb: `8GB RAM+256GB <br class="mob" />ROM`,
    descb: "Large Storage. Flagship Experience.",
  },
  sec12: {
    title: `6.78" FHD Display<br class="mob"/> with 120Hz Refresh<br class="mob"/> Rate`,
    sub: "Never Miss A Frame",
    desc: `1080*2460 Resolution. Up to 580typ Brightness.<br class="mob"/> Smooth Motion. Sharp View.`,
    p1a: "240Hz",
    p1b: "Touch Sampling Rate",
    p2a: "580nits",
    p2b: "Maximum Brightness",
  },
  sec13: {
    title: `12979mm² Ultra<br class="mob"/> Large Heat<br class="mob"/> Dissipation Area`,
    sub: "Conquer the Heat, Win the Battle!",
    desc: `2820 mm² Vapor Chamber Cooling+10159mm² Graphene heat sink<br class="pc"/> Dual Heat Dissipation, Double the Thermal Performance!`,
  },
  sec14: {
    title: "Empowered by Hard Gyroscope",
    sub: "Be the Sharpshooter!",
    desc: "Vibration adapted exclusively for FREEFIRE. Get steady aim, and precise hit!",
  },
  sec15: {
    title: "Dual Speaker with  DTS& Hi-Res",
    sub: "Hear the Sound, Step into the Scene",
    desc: `Experience immersive and full-bodied sound certified by DTS and Hi-Res. Enjoy the pure audio quality that<br class="mob"/> restores the essence of sound.`,
  },
  sec16: {
    title: "Brilliance Captured in Clarity",
  },
  sec17: {
    title: "50MP AI Camera",
    sub: "Capture Your Coolest Moments",
    desc: `Cool moments don't wait. Capture them with 50MP AI camera! See <br class="pc"/>ultra-clear images that bring your coolest moments to life`,
  },
  sec18: {
    titlea: "Portrait Beauty",
    titleb: "HDR mode",
  },
  sec19: {
    title: "Sky Shop",
    sub: "Finger-cast Magic Spells",
    desc: `Choose from over 12 sky-themed filters to create your <br class="mob"/>one-of-a-kind <br class="pc"/>photos, magically with just one tap!`,
    p1: "Sunny",
    p2: "Sunset",
    p3: "Aurora",
    p4: "Orbit",
  },
  sec20: {
    title: "Front and Back, <br />On At Once.",
    sub: "Vlog Your Life from Both Sides!",
    desc: `No need to shoot twice! Capture everything<br class="mob"/> effortlessly with the front+back dual-camera<br class="mob"/> setup. Create fun and interactive on-the-go<br class="mob"/> videos that reflect your creativity in travel, <br />work, and play.`,
  },
  sec21: {
    title: "Show Your Colorful Side",
  },
  sec22: {
    title: "HIOS13 New Interaction, New Experience",
    sub: "—Based on Android 13",
  },
  sec23: {
    title: "Colorful LED Ambient Light",
    sub: "Light up Your Vitality",
    desc: `Explore a range of dynamic visual effects with POVA's cool breathing LED lights <br class="pc"/>on the back. Power-on, message notification, charging, gaming, music, face-down, <br class="pc"/>or low battery, every mode has its unique lighting pattern.`,
    p1: "Incoming Calls",
    p2: "Charging",
    p3: "Startup",
    p4: "Games",
    p5: "Notifications",
  },
  sec24: {
    titlea: `Turbo Charged <br class="mob"/>Engine`,
    titleb: "Smooth, Extended Endurance",
    titlec: "UPS-Ultra Power Signal",
    desc: "Enjoy optimized performance with <br />increased cellular",
    p1: "Signal  Throughput",
    p2: "Signal Stability",
    p3: "Data Rate under <br />Weak Connection",
    p4: "Network <br />Acceleration",
  },
  sec25: {
    title: "Linkbooming 1.0",
    sub: "Dual network collaboration helps internet speeds take flight",
    desc: "Say goodbye to mobile network lagging. Linkbooming 1.0 enables parallel acceleration of Wi-Fi and cellular network connections for a fast and stable network experience.",
    p1: "Latency 25%",
    p2: "Network Speed 25%",
  },
  sec26: {
    title: "Smart 5G 2.0",
    sub: "Intelligent scheduling -- a ticket to the future",
    desc: `Smart5G 2.0 recognizes usage scenarios and analyzes <br class="mob"/> the current network <br class="pc"/>environment to intelligently switch <br class="mob"/> between 4G and 5G. This reduces power <br class="pc"/>consumption <br class="mob"/> and extends battery life.`,
  },
  sec27: {
    titlea: "Guardian of Safe Charging",
    titleb: "Triple Protection Instilled. Charge with Confidence.",
    titlec: "Battery Lab 3.0",
    sub: "More Power-Efficient, More Time Enjoying",
    desc: "Maximize battery life with POVA's power punch! Activate <br />Super Power Saving mode in a click to extend standby time; Adopt targeted power policies for different usage scenarios.",
    p1: "Long Battery <br />Life",
    p2: "Optimization  <br />App",
    p3: "Super Power  <br />Saving",
    p4: "Smart Power  <br />Saving Scenarios",
  },
  sec28: {
    title: "Bypass Charge",
    sub: "Keep Calm and Game On",
    desc: `Keep your phone cool when gaming and <br class="mob"/>charging at once. Bypass charge directs power<br class="mob"/> to the motherboard while high-power battery<br class="mob"/> remains in sleep mode to prevent overheating<br class="mob"/> and extend battery life.`,
  },
  sec29: {
    title: "Charging Port Monitoring",
    sub: "Unable to Charge? Beware of Liquid or Foreign Objects!",
    desc: `Pop-ups keep you alerted for any liquid or foreign<br class="mob"/> objects detected in <br class="pc"/>the charging port, preventing<br class="mob"/> potential hazards.`,
  },
  sec30: {
    title: "Game Space 2.0",
    sub: "Enjoy Gaming Time",
    desc: `Cool interface upgrade, a variety of modes extremely fast switching. <br class="pc"/>New performance radar chart, performance improvement is clear.`,
  },
  sec31: {
    title: "Panther Engine 3.0",
    sub: "AI-powered Temperature Control, Unleash Performance to the Full!",
    desc: "One-click temperature control with smart temperature <br />sensing: stabilizes gaming frame rate, improves gaming <br />fluency, extends gaming usage, and saves power <br />consumption!",
  },
  sec32: {
    title: `FIND MORE ABOUT${"\u00A0"}<a href='' target='_blank'>HiOS13</a>`,
    // sub: "link",
    // url: "",
    p1: `Smart <br class="mob"/>Refresh<br class="pc"/> 3.0`,
    p2: `Aurora <br class="mob"/> Engine <br /> ${"\u00A0"}`,
    p3: `Extended RAM <br /> ${"\u00A0"}`,
    p4: `Ella <br /> ${"\u00A0"}`,
    p5: "High Resolution <br />Audio",
    p6: `Mobile Cloner <br /> ${"\u00A0"}`,
    p7: "Exclusive AI Noise <br />Cancelation",
    p8: `My <br class="mob"/> Health <br /> ${"\u00A0"}`,
  },
  sec2video: {
    // 竖版
    vpath: "http://127.0.0.1:5173/src/assets/video/sec2V.mp4",
    vpost: "http://127.0.0.1:5173/src/assets/post/sec2V.png",
    // 横版
    hpath: "http://127.0.0.1:5173/src/assets/video/sec2H.mp4",
    hpost: "http://127.0.0.1:5173/src/assets/post/sec2H.png",
  },
  sec10video: {
    path: "http://127.0.0.1:5173/src/assets/video/sec10.mp4",
    post: "http://127.0.0.1:5173/src/assets/post/sec10H.png",
  },
  sec11video: {
    path: "http://127.0.0.1:5173/src/assets/video/sec11.mp4",
    post: "http://127.0.0.1:5173/src/assets/post/sec11H.png",
  },
  sec12video: {
    path: "http://127.0.0.1:5173/src/assets/video/sec12.mp4",
    post: "http://127.0.0.1:5173/src/assets/post/sec12H.png",
  },
  sec13video: {
    path: "http://127.0.0.1:5173/src/assets/video/sec13.mp4",
    post: "http://127.0.0.1:5173/src/assets/post/sec13H.png",
  },
  sec15video: {
    path: "http://127.0.0.1:5173/src/assets/video/sec15.mp4",
    post: "http://127.0.0.1:5173/src/assets/post/sec15H.png",
  },
  sec20video: {
    path: "http://127.0.0.1:5173/src/assets/video/sec20.mp4",
    post: "http://127.0.0.1:5173/src/assets/post/sec20H.png",
  },
  sec23video: {
    // 来电
    calling: "http://127.0.0.1:5173/src/assets/video/calling.mp4",
    callingpost: "",
    // 游戏
    game: "http://127.0.0.1:5173/src/assets/video/game.mp4",
    gamepost: "",
    // 开机
    open: "http://127.0.0.1:5173/src/assets/video/open.mp4",
    openpost: "",
    // 消息
    message: "http://127.0.0.1:5173/src/assets/video/message.mp4",
    messagepost: "",
    // 充电
    charge: "http://127.0.0.1:5173/src/assets/video/charge.mp4",
    chargepost: "",
  },
  sec30video: {
    path: "http://127.0.0.1:5173/src/assets/video/sec30.mp4",
    post: "http://127.0.0.1:5173/src/assets/post/sec30V.webp",
  },
  sec8frames: {
    path: "http://127.0.0.1:5173/src/assets/frame/ani1",
  },
}
