// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore

window.pop8Config = {
  VITE_FRAMES_URL: '/fileadmin/sitedesign/product/SPARK_20C/dist',
  sec1: {
    icon1Top: "52%",
    icon1Left: "55%",
    icon1MobTop: "52%",
    icon1MobLeft: "83%",
  },
  sec2: {
    t1: `6.6" 90Hz Hole Screen <br/> Self-developed Dynamic Port`,
    t2: "Minimalist <br/> Square <br/> Shape",
    t3: "Large Storage <span>1TB</span> Extended SD Card",
    t4: "5000mAh Large Battery with 18W Fast Charge",
    t5: "Side Edge Fingerprint Unlocking",
    t6: "Stereo Dual Speaker Sound by DTS <br /> 400% Big Volume",
    t7: "Camera",
  },
  sec3: {
    text: "Aesthetics",
    title: "Dual Textures,<br/> Next-level <br/> Allure",
    icon1Top: "-7%",
    icon1Left: "-8%",
    icon1MobTop: "-7%",
    icon1MobLeft: "-16%",
    t1: "Minimalist Square Shape",
    d1: "Prep for a posh texture and design overhaul! The slim body comes in<br /> two styles: Rainbow Ring for a pop of color burst; And Magic Skin 2.0<br /> for a luxury sensation that feels like premium leather - crafted from 100%<br /> hazard-free high-polymer silicone!<br /> Pick your look and feel. Level up your style!",
    param1t: "8.55mm",
    param1d: "Ultra Slim",
    param2t: "Sparkle Sand",
    param2d: "New Generation",
    param3t: "Million Colour",
    param3d: "Coating",
    param4t: "8.75mm",
    param4d: "Ultra Slim",
    param5t: `Magic<br /> Skin 2.0`,
    param5d: "Leather",
    param6t: `100%<br /> Recyclable`,
    param6d: `Back Cover`,
    param7t: `Zero`,
    param7d: `Harmful<br /> Substance`,
    tips: "*Evidenced by data from TRANSSION LAB",
  },
  sec4: {
    title: "Sail Seamlessly in a Wider Wonderland.",
    icon3Top: "17%",
    icon3Left: "92%",
    icon3MobTop: "5%",
    icon3MobLeft: "95%",
    t1: `6.6'' 90Hz Hole Screen`,
    d1: `Explore a vast wonderland on a 6.6-inch<br /> ultra-wide display! At a whopping 90.5% <br />screen-to-body ratio - a rarity in its class,<br /> feel like floating on a boundless sea of<br /> visual feast! It's a seamless adventure, as <br />90Hz high-refresh rate guarantees ultra-<br />responsive interactions! <br />Surprises await between each tap.`,
    param1t: `6.6'' Hole`,
    param1d: "Large Screen",
    param2t: "90Hz",
    param2d: "Refresh Rates",
    param3t: "8H",
    param3d: "Surface Hardness",
    tips: "*Evidenced by data from TRANSSION LAB",
  },
  sec5: {
    title: "Beauty + Utility <br/> Best of Both Worlds",
    icon1Top: "14%",
    icon1Left: "-12%",
    icon1MobTop: "-23%",
    icon1MobLeft: "-21%",
    t1: "Self-developed Dynamic Port",
    d1: `Welcome aboard TECNO's ingenious Dynamic Port,<br class='pc'/> seamlessly integrated into the screen display. Intuitive UI<br class='pc'/> brings efficient notifications - Stay in the know without<br class='pc'/> frequent unlocking, checking, or app switching. Traditional<br class='pc'/> mode is also available for your flexibility. <br /> Experience simplified, but not compromised!`,
  },
  sec6: {
    text: "Image",
    title: "Front + Back <br/> Clarity on Both <br/> Ends",
    icon4Top: "-2%",
    icon4Left: "62%",
    icon4MobTop: "-14%",
    icon4MobLeft: "85%",
    t1: "8MP Dual Flash Selfie",
    d1: "Dusk to dawn, in or out, selfie master on the front is always<br class='pc'/> here to deliver! 8MP camera for sharp clarity, with light-sensitive<br class='pc'/> pixel, dual flash ,and screen fill light for your radiant glow. Plus<br class='pc'/> battle-tested beauty enhancements for every skin tone!<br class='pc'/> Step into the spotlight and let your inner star be doubly shine.",
    param1t: "Super Night",
    param1d: "Algorithm",
    param2t: "8MP",
    param2d: "Ultra Clear Selfie",
    param3t: "1.12μm",
    param3d: "Ultra Large Pixel Unit",
    param4t: "Dual Flash Light",
    param4d: "Natural Lighting",
    tips: "*Pictures are for illustration only, please refer to the actual product form.",
  },
  sec7: {
    t1: "50MP HDR Ultra Sensitive Camera",
    d1: "Capture fleeting wonders anytime with 50MP main camera. From daylight adventures to backlit beauty, it excels. HDR merges frames for clarity to outshine, while ultra-large light-sensitive pixel unit and optical-improving 6P lens reveal captivating details amidst light and shadow at night. And thanks to PDAF that guarantees swift focus, not a single exceptional moment will be missed!",
    param1t: "50MP",
    param1d: "Ultra Clear",
    param2t: `1/2.8"`,
    param2d: "Ultra Large <br /> Sensor",
    param3t: "6P",
    param3d: "High light <br /> Transmission",
    param4t: "PDAF",
    param4d: "Phase Detection <br /> Auto-focus",
    param5t: "HDR Effect",
    param5d: "Multi-frame Fusion",
    tips: "*Pictures are for illustration only, please refer to the actual product form.",
  },
  sec8: {
    title: "Eyes on You!",
    icon2Top: "-41%",
    icon2Left: "23%",
    icon3Top: "2%",
    icon3Left: "-8%",
    icon2MobTop: "-41%",
    icon2MobLeft: "34%",
    icon3MobTop: "-21%",
    icon3MobLeft: "-21%",
    t1: "AR Shot",
    d1: "Express your vibrant self with playful cartoon avatars,<br class='mob'/> lively backgrounds, and a variety of AR elements. <br/> Stand out and steal the show!",
    tips: "*Videos are for illustration only, please refer to the actual product form.",
  },
  sec9: {
    title: "Performance",
  },
  sec10: {
    bigTitle: `Double Beat, Over <br class='pc'/>Double the Treat!`,
    icon1: {
      top: "-26%",
      left: "-9%",
      mobtop: "-34%",
      mobleft: "3%",
    },
    icon4: {
      top: "-9%",
      left: "86%",
      mobtop: "-2%",
      mobleft: "83%",
    },

    title: `Stereo Dual Speaker <br /> Sound by DTS <br /> 400% Big Volume`,
    desc: `Up your mobile audio experience to theatre-level with dual speakers! DTS LISTEN envelops you in the stereo sound like melodies have come to life around you. Adaptive channels ensure clarity during flips, perfect for gaming. And enjoy crystal-clear calls even in noisy environments with double the enhanced volume.<br />
    Elevate to the audio luxury you deserve today!`,
    p1a: `Stereo Dual <br /> Speakers`,
    p1b: `Loudness Enhancement`,
    p2a: `Audio <br />Booster`,
    p2b: `Calling Assistant`,
    p3a: `Binaural <br /> Tracing `,
    p3b: `Technology`,
    p4a: `Volume <br /> Plus`,
    p4b: `loud sound`,
    tips: `*Pictures are for illustration only, please refer to the actual product form. <br /> *Some products require a system update to experience Volume Plus.`,
  },
  sec11: {
    bigTitle: `No Trouble,<br /> Just Double!`,
    icon3: {
      top: "56%",
      left: "57%",
      mobtop: "41%",
      mobleft: "64%",
    },

    title: `Large Storage with <br class='pc'/> System Slimming`,
    desc: `No more tradeoff! With spacious memory, keep all your loved music and cherished photos, tested to save nearly 10,000 pics. Up to 8GB extended memory enhances seamless operations, with System Slimming to keep it clean and clutter-free.<br /> Leave lag behind. Keep only speed, smoothness, and stability.`,
    p1a: `Up to 1TB`,
    p1b: `Extended Storage`,
    p2a: `Up to 16GB`,
    p2b: `Memory Fusion`,
    p3a: `System Slimming`,
    p3b: `Deep Cleanup`,
    tips1: `*Up to 16GB, 8GB+8GB Extended RAM`,
    tips2: `*The 1TB extended storage is only available on models with a 1TB MicroSD card. Actual storage available may vary depending on pre-installed software.`,
    tips3: `*MicroSD card must be purchased separately and is not included in this product.`,
    tips4: `*Pictures are for illustration only, please refer to the actual product form.`,
    tips5: `*Evidenced by data from TRANSSION LAB`,
  },
  sec12: {
    bigTitle: `Double Down <br /> On Power!`,
    icon1: {
      top: "7%",
      left: "63%",
      mobtop: "56%",
      mobleft: "67%",
    },
    icon2: {
      top: "-35%",
      left: "27%",
      mobtop: "-55%",
      mobleft: "38%",
    },
    icon3: {
      top: "7%",
      left: "63%",
      mobtop: "-1%",
      mobleft: "72%",
    },

    title: `5000mAh <br class='pc'/> Large Battery <br class='pc'/> with 18W Fast Charge <br class="pc"/>(Type-C)`,
    desc: `Say goodbye to power anxiety with a mega, marathon battery with over 600 hours of standby time, which comes back quick with 18W fast charge. Dive into non-stop videos and music, which can play videos for 15.5 hours and music for 73.5 hours on a full charge. The versatile Type-C port plays along – up or down, plug it in any way you want. A feature usually reserved for pricier models - level up your experience, level down your costs!`,
    p1a: `5000mAh`,
    p1b: `Large Battery`,
    p2a: `18W`,
    p2b: `Fast Charge`,
    p3a: `Type-C`,
    p3b: `Interface`,
    tips: `*Pictures are for illustration only, please refer to the actual product form. <br />
    *Evidenced by data from TRANSSION LAB`,
  },
  sec13: {
    bigTitle: `Half the Effort,<br />Tip Awake a Smart<br /> World`,
    icon1: {
      top: "-15%",
      left: "-14%",
      mobtop: "-15%",
      mobleft: "1%",
    },
    icon2: {
      top: "-3%",
      left: "85%",
      mobtop: "-8%",
      mobleft: "82%",
    },
    icon3: {
      top: "-2%",
      left: "-12%",
      mobtop: "-9%",
      mobleft: "1%",
    },

    title: `Side Edge Fingerprint Unlocking`,
    desc: `Leading the range with leading-edge side-mounted fingerprint<br class='pc'/> sensor. Unlock intuitively, and elegantly. No lifting or fumbling.<br class='pc'/> A gentle touch with fingertip - Voila, your device is ready at<br class='pc'/> your service.`,
    p1a: `Millisecond Grade`,
    p1b: `Unlocking Speed`,
    p2a: `About 10mm²`,
    p2b: `Large Sensor Area`,
    tips: `*Evidenced by data from TRANSSION LAB`,
  },
  sec14: {
    bigTitle: `Race for<br /> Milliseconds, on<br /> Duo Drive.`,
    icon1: {
      top: "0%",
      left: "-15%",
      mobtop: "0%",
      mobleft: "4%",
    },
    icon2: {
      top: "-17%",
      left: "40.5%",
      mobtop: "-17%",
      mobleft: "51.5%",
    },
    icon3: {
      top: "35%",
      left: "70%",
      mobtop: "35%",
      mobleft: "80%",
    },

    title: `Octa-core Processor`,
    desc: `Powered by octa-core Arm Cortex-A53 processor, offering up to 2.2GHz peak frequency for lighteing-fast mobile experience! While the self-developed Darwin Engine keeps your device cool so you chill in longer usage.<br /> 
    Enjoy uninterrupted, silky-smooth performance without a hitch!`,
    p1a: `2.2GHz`,
    p1b: `Peak Frequency`,
    p2a: `Octa-core Arm Cortex-A53`,
    p2b: `Processor`,
    tips: `*Pictures are for illustration only, please refer to the actual product form.`,
  },
  sec15: {
    bigTitle: `AI Voice Assistant - Your <br /> Go-To Companion for <br /> Anything`,
    icon1: {
      top: "-30%",
      left: "-12%",
      mobtop: "0%",
      mobleft: "4%",
    },

    title: `AI Voice Assistant with ChatGPT`,
    desc: `Meet your trusty smart assistant, packed with the incredible ChatGPT intelligence! Stay ahead by accessing the latest tech wonder with it. From chitchat to poetry or music, this Voice Assistant gets you to the limitless AI potential.`,
    tips: `*Pictures are for illustration only, please refer to the actual product form.`,
  },



   // type1: 文案+图片   (文案字段: 在sec1Text下面, 图片字段: sec1Type1ImagePc(pc端)、sec1Type1ImageMob(移动端));
  // type2: 文案+小视频 (文案字段: 在sec1Text下面, 小视频字段: sec1Video.pcType2(pc端)、sec1Video.mobType2(移动端), 视频海报图: type2Post(pc端)、type2PostMob(移动端));  
  // type3: 通屏大视频  (大视频字段: sec1Video.pcType3(pc端)、sec1Video.mobType3(移动端), 视频海报图: type3Post(pc端)、type3PostMob(移动端));
  // type4: 通屏大图片(图片字段: sec1Type4ImagePc(pc端)、sec1Type4ImageMob(移动端))
  sec1Type: 'type4',
  sec1Text: {
    title: `Double Up,<br /> Level Up`,
    p1: "Double <span></span> <br/> Speakers",
    p2: "50MP <br/> Camera",
    p3: "Up to <span>8+8 GB <br/> Extended RAM</span><br/> 128GB+16GB* ",
    p4: "18W <br/> Fast Charge",
    tips: "128GB ROM+8GB RAM*(4GB+4GB Extended) <br/> 128GB ROM+16GB RAM*(8GB+8GB Extended)",
  },
  sec1Type1ImagePc: '/fileadmin/sitedesign/product/SPARK_20C/dist/png/sec1PcBg.png',
  sec1Type1ImageMob: '/fileadmin/sitedesign/product/SPARK_20C/dist/png/sec1MobBg.png',
  sec1Video: {
    pcType2: "/fileadmin/sitedesign/product/SPARK_20C/dist/video/sec1PcType2.mp4",
    mobType2: "/fileadmin/sitedesign/product/SPARK_20C/dist/video/sec1PcType2.mp4",
    pcType3: "/fileadmin/sitedesign/product/SPARK_20C/dist/video/sec1PcFull.mp4",
    mobType3: "/fileadmin/sitedesign/product/SPARK_20C/dist/video/sec1MobFull.mp4",
    type2Post: "",
    type2PostMob: "",
    type3Post: "",
    type3PostMob: "",
  },
  sec1Type4ImagePc: '/fileadmin/sitedesign/product/SPARK_20C/dist/jpg/sec1PcKv_my.jpg',
  sec1Type4ImageMob: '/fileadmin/sitedesign/product/SPARK_20C/dist/jpg/sec1PcMb_my.jpg',
  //type1 有两屏切换, type2 只有一屏
  sec3Type: 'type2',
  sec6Image: {
    pic1: "/fileadmin/sitedesign/product/SPARK_20C/dist/png/sec7MbF4.png"
  },
  sec6Video: {
    pc: "/fileadmin/sitedesign/product/SPARK_20C/dist/video/sec6Pc.mp4",//白人
  },
  sec7Video: {
    pc: "/fileadmin/sitedesign/product/SPARK_20C/dist/video/sec7Pc.mp4",
    mob: "/fileadmin/sitedesign/product/SPARK_20C/dist/video/sec7Mob.mp4",
    v1PostMob: "/fileadmin/sitedesign/product/SPARK_20C/dist/jpg/sec7MobPoster.jpg",
  },
  sec8Video: {
    // 线上
    v1: "/fileadmin/sitedesign/product/SPARK_20C/dist/video/sec8V1.mp4",
    v1Post: "/fileadmin/sitedesign/product/SPARK_20C/dist/jpg/sec8V1Poster.jpg",
    v2: "/fileadmin/sitedesign/product/SPARK_20C/dist/video/sec8V2.mp4",
    v2Post: "/fileadmin/sitedesign/product/SPARK_20C/dist/jpg/sec8V2Poster.jpg",
    v3: "/fileadmin/sitedesign/product/SPARK_20C/dist/video/sec8V3.mp4",
    v3Post: "/fileadmin/sitedesign/product/SPARK_20C/dist/jpg/sec8V3Poster.jpg",
    v4: "/fileadmin/sitedesign/product/SPARK_20C/dist/video/sec8V4.mp4",
    v4Post: "/fileadmin/sitedesign/product/SPARK_20C/dist/jpg/sec8V4Poster.jpg",
    v5: "/fileadmin/sitedesign/product/SPARK_20C/dist/video/sec8V5.mp4",
    v5Post: "/fileadmin/sitedesign/product/SPARK_20C/dist/jpg/sec8V5Poster.jpg",
    v6: "/fileadmin/sitedesign/product/SPARK_20C/dist/video/sec8V6.mp4",
    v6Post: "/fileadmin/sitedesign/product/SPARK_20C/dist/jpg/sec8V6Poster.jpg",
  },
  sec11Video: {
    pc: "/fileadmin/sitedesign/product/SPARK_20C/dist/video/sec11Pc.mp4",
  },
  sec12Video: {
    pc: "/fileadmin/sitedesign/product/SPARK_20C/dist/video/sec12Pc.mp4",
    mob: "/fileadmin/sitedesign/product/SPARK_20C/dist/video/sec12Mob.mp4",
  },
}
