const lan = {
  section1: {
    f1: "7000mAh Mega Battery",
    f2: "18W Flash Charge",
    f3: "MTK G85 Processor",
    f4: "128GB ROM + 8GB RAM",
  },
  section2: {
    f1a: "Innovative",
    f1b: "Design",
    f2a: "Stunning",
    f2b: "Power",
    f3a: "Stunning",
    f3b: "Power",
    f4a: "Clear",
    f4b: "Camear",
    f5: "HIOS 13",
  },
  section4: {
    f1: "Brand",
    f2: "New",
    f3: "Mecha",
    f4: "Design",
  },
  section5: {
    titlea: "Turbor Mecha",
    titleb: "Design",
    slogan: "Energize Your Coolness",
    desc: "Inspired by energy Mecha, the power-packed POVA NEO 3 comes with three color options for an energizing experience!",
    texta: "Life-like 3D Mecha Design",
    textb: "with Turbo Stripes",
  },
  section6: {
    f1a: "Amber",
    f1b: "Gold",
    f2a: "Mecha",
    f2b: "Black",
    f3a: "Hurricane",
    f3b: "Blue",
  },
  section7: {
    f1: "Power On",
    f2: "and On",
    f3: "Play ",
    f4: "Non-stop",
  },
  section8: {
    titlea: "7000mAh",
    titleb: "Mega Battery",
    desca:
      "Boldly engage in battles with the 7000mAh battery, which provides powerful backup for uninterrupted gaming sessions. Combined with the added benefit of 18W Flash Charge, say goodbye to power shortages from now on.",
    pa: "18H+",
    pat: "Facebook",
    pb: "14H+",
    pbt: "Watch video",
    pc: "11H+",
    pct: "Play FREEFIRE",
    pd: "39H+",
    pdt: "Calls",
    titlec: "STS Secure",
    titled: "Battery",
    titlee: "Technology",
    sub: "The Power You Can Trust",
    descb:
      "The STS coating technology ensures safety by preventing dangerous internal short circuits caused by direct contact between aluminum foil and anode, providing you with complete peace of mind.",
  },
  section9: {
    titlea: "Battery",
    titleb: "Lab 3.0",
    desca:
      "Extend your phone's battery life with the new energy-efficient Super",
    descb: "Power Saver. It intelligently identifies battery-draining apps and",
    descc: "adjusts to the best power-saving mode for longer use.",
    pa1: "Long Battery",
    pa2: "Life",
    pb1: "Optimization",
    pb2: "App",
    pc1: "Super Power",
    pc2: "Saving",
    pd1: "Smart Power",
    pd2: "Saving Scenarios",
  },
  section10: {
    f1: "Pioneering",
    f2: "Performance",
    f3: "Supercool",
    f4: "Experience",
  },
  section11: {
    titlea: "MediaTek Helio G85",
    titleb: "Processor",
    suba: "Gaming Experience Revamped",
    desca:
      " The MediaTek Helio G85 boosts the Arm Mali-G52 GPU to 1.0 GHz for seamless and efficient mobile gaming on-the-go.",
    subb: "Navigate with Precision",
    descb:
      "Boasting leading inertial navigation, Helio G85 ensures precise positioning even in tunnels or underground where GNSS is unavailable.",
  },
  section12: {
    titlea: "Large",
    titleb: "Memory With",
    titlec: "Extended",
    titled: "RAM",
    suba: "128+4GB",
    subb: "128+8GB",
    desc1a: "• Expandable RAM up to 8GB",
    desc1b: " *Optional expansion of 1, 2, 4GB, default expansion of 2GB",
    desc1c: "•The number of active background apps reaching 11",
    desc1d: "• Application startup speed increased by 45% on average",
    desc2a: "• Expandable RAM up to 16GB",
    desc2b: "*Optional expansion of 3, 5, 8GB, default expansion of 5GB",
    desc2c: " •The number of active background apps reaching 20",
    desc2d: "•Application startup speed increased by 55% on average",
  },
  section13: {
    titlea: "6.82'' HD Display",
    titleb: "with 90Hz",
    titlec: "Refresh Rate",
    desc: "Get the most out of your gaming experience with an enhanced experience that features smoother graphics, richer detail, and total immersion.",
  },
  section14: {
    titlea: "Dual speaker",
    titleb: "with DTS",
    titlec: "Stereo Sound",
    titled: "Effect",
    desc: "Hear the super sensational sound effects that will transport you into the game world like never before.",
  },
  section15: {
    title: "Dual Game Engine",
    desca: "Powerful Function with Low Power Consumption.",
    descb:
      " Enjoy seamless, lag-free mobile gaming with stunningly realistic visuals and immersive sounds.",
  },
  section16: {
    f1: "Clear",
    f2: "Camera",
    f3: "Meets",
    f4: "Your Shine",
  },
  section17: {
    titlea: "16MP",
    titleb: "Clear Main Camera",
    desc: "Capture life's beauty.",
  },
  section19: {
    titlea: "Amplify your brilliance",
    titleb: "with Portrait Beauty",
    titlec: "feature",
  },
  section20: {
    title: "SKY SHOP",
    sub: "Magic at Your Fingertip",
    desc: "Choose from over 12 sky-themed filters to create your one-of-a-kind photos, magically with just one tap!",
    f1: "Sunny",
    f2: "Sunset",
    f3: "Sunny",
    f4: "Orbit",
  },
  section21: {
    titlea: "Show Your",
    titleb: "Colorful Side",
  },
  section22: {
    f1: "Clear",
    f2: "Camera",
    f3: "Meets",
    f4: "Your Shine",
  },
  section23: {
    title: "Vivid Wallpapers",
    desca: "Treat your eyes to a tapestry of color and beauty.",
    descb:
      "A series of interconnected wallpapers merge objects and creatures from the real world and the imagination. Your",
    descc:
      "life is multicolored and ever-evolving, and your phone should reflect that.",
  },
  secPar: {
    titlePca: "UPS-Ultra ",
    titlePcb: "Power Signal",
    titleMob: "UPS-Ultra Power Signal",
    sub: "Enjoy Optimized Performance with Increased Cellular",
    num: "15-20%",
    desca: " Signal Throughput",
    descb: "Signal Stability",
    descc1: "Data Rate under Weak",
    descc2: "Connection",
  },
  section24: {
    titlea: "Linkbooming",
    titleb: "1.0",
    sub: "Dual Network Collaboration Helps Internet Speeds Take Flight",
    desca: "Say goodbye to mobile network lagging.",
    descb:
      "Linkbooming 1.0 enables parallel acceleration of Wi-Fi and cellular network connections for a fast and stable network experience.",
    texta: "Latency 25%",
    textb: "Network Speed 25%",
  },
  section25: {
    titlea: "Aurora",
    titleb: "Engine",
    sub: "Launch Apps in an Instant Battle-ready in Seconds",
    desc: "All-new Aurora Engine powered by AI algorithms delivers lightning-fast speed to launch top 10 large-scale games in seconds. Foreground launch rate up by 85%, enjoy seamless gameplay with no wait. Common App launch rate up by 95%, gain instant access and maximum efficiency.",
  },
  section26: {
    title: "Game Space 2.0",
    sub: "Enjoy Gaming Time",
    desca: "Cool interface upgrade. Instantly switch from a variety of modes.",
    descb:
      "View performance improvements in a glance with the new performance radar chart.",
  },
  section27: {
    titlea: "Find More About",
    titleb: "HIOS13",
    sub: "HIOS 13",
    f1a: "Panther",
    f1b: "Engine 2.0",
    f2a: "Lightning",
    f2b: "Multi-Window4.0",
    f3a: "Smart Refresh",
    f3b: "3.0",
    f4a: "Mobile",
    f4b: "Cloner",
    f5a: "Extended",
    f5b: "RAM",
    f6a: "Smart",
    f6b: "Scanner",
  },
}

export default lan
