

window.pop8Config = {
  VITE_FRAMES_URL: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist",
    sec1: {
      icon1Top: "52%",
      icon1Left: "88%",
      icon1MobTop: "52%",
      icon1MobLeft: "83%",
    },
    sec2: {
      t1: "Màn hình đục lỗ 90Hz 6,6''<br/> Dynamic Port phát triển bởi Tecno",
      t2: "Thiết kế tối giản",
      t3: "Thẻ SD mở rộng dung lượng lưu trữ lớn <span>1 TB</span>",
      t4: "Dung lượng Pin lớn 5.000 mAh với sạc Type-C",
      t5: "Mở khóa vân tay cạnh bên",
      t6: "Loa Kép dts 400% âm lượng",
      t7: "Camera",
    },
    sec3: {
      text: "Tính thẩm mỹ",
      title: " Kết cấu kép, <br/>Nâng cấp  <br/> vượt trội",
      icon1Top: "-7%",
      icon1Left: "-8%",
      icon2Top: "29%",
      icon2Left: "53%",
      icon3Top: "67%",
      icon3Left: "23.6%",
      icon1MobTop: "-7%",
      icon1MobLeft: "-16%",
      icon2MobTop: "29%",
      icon2MobLeft: "85%",
      icon3MobTop: "67%",
      icon3MobLeft: "37.6%",
      t1: "Thiết kế tối giản",
      d1: "Hãy sẵn sàng đón chờ một cuộc cải cách mạnh mẽ về kết cấu và thiết kế sang trọng! Thân máy gọn nhẹ với hai phong cách: Vòng cầu vồng bùng nổ màu sắc và Magic Skin 2.0 mang lại cảm giác sang trọng giống như chất liệu da thượng hạng - được chế tạo từ 100% silicon polyme cao cấp không độc hại! Tự lựa chọn kiểu dáng và chất liệu cho bản thân. Hãy nâng tầm phong cách của bạn!",
      param1t: "8,55 mm",
      param1d: "Siêu mỏng",
      param2t: "Cát lấp lánh",
      param2d: "Thế hệ mới ",
      param3t: "Hàng triệu màu",
      param3d: "Lớp phủ",
      param4t: "8,75 mm",
      param4d: "Siêu mỏng",
      param5t: `Magic <br /> Skin 2.0`,
      param5d: "Da",
      param6t: `100% có <br /> thể tái chế`,
      param6d: `Nắp lưng`,
      param7t: `Không`,
      param7d: `Chất <br />có hại`,
      tips: "*Được chứng minh bằng dữ liệu từ TECNO LAB",
    },
    sec4: {
      title: "Đắm chìm trong xứ xở thần tiên bao la.",
      icon1Top: "-18%",
      icon1Left: "-16%",
      icon2Top: "-29%",
      icon2Left: "36%",
      icon3Top: "35%",
      icon3Left: "92%",
      icon4Top: "69%",
      icon4Left: "-15%",
      icon3MobTop: "5%",
      icon3MobLeft: "95%",
      t1: `Màn hình đục lỗ 90 Hz 6,6''`,
      d1: `Khám phá xứ xở thần tiên rộng lớn trên màn hình siêu rộng 6,6 inch! Với tỷ lệ màn hình trên thân máy đạt 90,5% - một đặc điểm hiếm có trong cùng phân khúc, bạn sẽ được trải nghiệm cảm giác như đang lơ lửng trên một bữa tiệc thị giác vô tận! Đây là một cuộc phiêu lưu không rào cản với tần số quét lên tới 90 Hz, đảm bảo các tương tác siêu nhạy!
      Bất ngờ giữa mỗi lần chạm.`,
      param1t: `Màn hình lớn`,
      param1d: `Màn hình đục lỗ 6.6''`,
      param2t: "Tần số quét màn hình",
      param2d: "90Hz",
      param3t: "Độ cứng bề mặt",
      param3d: "8H",
      tips: "*Được chứng minh bằng dữ liệu từ TECNO LAB",
    },
    sec5: {
      title: "Mới lạ + Tiện lợi<br/> Vượt trội trên cả hai khía cạnh",
      icon1Top: "14%",
      icon1Left: "-12%",
      icon2Top: "-53%",
      icon2Left: "65%",
      icon3Top: "74%",
      icon3Left: "28.5%",
      icon4Top: "69%",
      icon4Left: "80%",
      icon1MobTop: "-23%",
      icon1MobLeft: "-21%",
      icon2MobTop: "-28%",
      icon2MobLeft: "89%",
      icon3MobTop: "59%",
      icon3MobLeft: "38%",
      icon4MobTop: "33%",
      icon4MobLeft: "70%",
      t1: "Dynamic Port phát triển bởi Tecno",
      d1: `Chào mừng bạn đến với Dynamic Port của TECNO, được tích hợp liền mạch vào màn hình hiển thị. Giao diện người dùng trực quan giúp xem thông báo hiệu quả - Luôn cập nhật thông tin mà không cần phải thường xuyên mở khóa màn hình, kiểm tra điện thoại hoặc chuyển đổi giữa các ứng dụng. Chế độ truyền thống cũng được trang bị nhằm đảm bảo sự linh hoạt của bạn. 
      Trải nghiệm đơn giản nhưng không tầm thường!`,
    },
    sec6: {
      text: "Hình ảnh",
      title: "Mặt trước + Mặt sau<br/> Cả hai camera đều  <br/> rõ nét",
      icon1Top: "55%",
      icon1Left: "-13.7%",
      icon2Top: "-26%",
      icon2Left: "26%",
      icon3Top: "55%",
      icon3Left: "28%",
      icon4Top: "15%",
      icon4Left: "90%",
      icon1MobTop: "55%",
      icon1MobLeft: "-13.7%",
      icon2MobTop: "-26%",
      icon2MobLeft: "26%",
      icon3MobTop: "55%",
      icon3MobLeft: "28%",
      icon4MobTop: "-14%",
      icon4MobLeft: "85%",
      t1: "Ảnh selfie với đèn flash kép 8MP",
      d1: "Dù chụp trong bối cảnh hoàng hôn hay bình minh, trong nhà hay ngoài trời, camera trước selfie luôn đáp ứng yêu cầu của bạn! Camera 8 MP đảm bảo độ sắc nét, với điểm ảnh nhạy sáng, đèn flash kép và tính năng hắt sáng toàn màn hình giúp bạn tỏa sáng rực rỡ. Kết hợp với các tính năng làm đẹp đã được thử nghiệm cho mọi tông da! Hãy đứng dưới ánh đèn sân khấu và để vẻ đẹp tiềm ẩn bên trong bạn tỏa sáng rực rỡ.",
      param1t: "Chụp đêm nâng cao ",
      param1d: "Thuật toán",
      param2t: "8MP",
      param2d: "Ảnh Selfie siêu rõ nét",
      param3t: "1.12 μm",
      param3d: "Đơn vị điểm ảnh cực lớn",
      param4t: "Đèn flash kép",
      param4d: "Ánh sáng tự nhiên",
      tips: "*Hình ảnh chỉ mang tính chất minh họa, vui lòng tham khảo mẫu sản phẩm thực tế.",
    },
    sec7: {
      t1: "Camera chân dung HDR 13MP",
      d1: "Khẩu độ siêu rộng + Đơn vị điểm ảnh siêu lớn. Hãy để bộ đôi camera SUPER DUO ở mặt sau nâng tầm những bức ảnh chân dung của bạn trong mọi điều kiện ánh sáng. Không thể lu mờ ngay cả khi chụp ngược sáng! HDR kết hợp các khung hình để mang lại độ rõ nét vượt trội, ngoài ra tính năng làm mờ hậu cảnh tạo dựng sân khấu để bạn trở thành ngôi sao. Ghi lại vẻ đẹp mọi lúc, mọi nơi.",
      param1t: "13MP",
      param1d: "Siêu rõ nét",
      param2t: "Hiệu ứng<br/> HDR",
      param2d: "Kết hợp nhiều khung hình",
      param3t: "F/1.8",
      param3d: "Khẩu độ rộng",
      param4t: "1.12 μm",
      param4d: "Đơn vị điểm ảnh cực lớn",
      tips: "*Hình ảnh chỉ mang tính chất minh họa, vui lòng tham khảo mẫu sản phẩm thực tế.",
    },
    sec8: {
      title: "Thu hút MỌI ánh nhìn!",
      icon1Top: "-21%",
      icon1Left: "-8%",
      icon2Top: "-41%",
      icon2Left: "45%",
      icon3Top: "2%",
      icon3Left: "-8%",
      icon1MobTop: "-21%",
      icon1MobLeft: "-12%",
      icon2MobTop: "-41%",
      icon2MobLeft: "34%",
      icon3MobTop: "-21%",
      icon3MobLeft: "-21%",
      t1: "Chụp ảnh AR",
      d1: "Hãy thể hiện cá tính của bản thân với bức ảnh đại diện hoạt hình vui nhộn, hình nền sống động và nhiều tính năng AR khác. Hãy nổi bật theo cách riêng của bạn!",
      tips: "*Video chỉ mang tính chất minh họa, vui lòng tham khảo mẫu sản phẩm thực tế.",
    },
    sec9: {
      title: "Hiệu suất",
    },
    sec10: {
      bigTitle: `Gấp đôi nhịp điệu, <br class='pc'/>tận hưởng bữa tiệc âm thanh sống động!`,
      icon1: {
        top: "-26%",
        left: "-9%",
        mobtop: "-34%",
        mobleft: "3%",
      },
      icon2: {
        top: "-57%",
        left: "58%",
        mobtop: "-36%",
        mobleft: "68%",
      },
      icon3: {
        top: "74%",
        left: "-8%",
        mobtop: "49%",
        mobleft: "7%",
      },
      icon4: {
        top: "-9%",
        left: "86%",
        mobtop: "-2%",
        mobleft: "83%",
      },
  
      title: `Âm thanh loa kép DTS<br class='pc'/> Âm lượng lớn 400%`,
      desc: `Nâng tầm trải nghiệm âm thanh trên thiết bị di động giống như trải nghiệm trong rạp hát với loa kép! Thưởng thức âm nhạc hoặc xem video như thể đang có mặt tại buổi biểu diễn trực tiếp, với những giai điệu sống động bao quanh bạn. Ngoài ra, bạn có thể tận hưởng âm thanh cuộc gọi rõ nét ngay cả trong môi trường ồn ào với âm lượng tăng cường gấp đôi.`,
      p1a: `Loa kép âm <br /> thanh nổi`,
      p1b: `Tăng cường âm lượng`,
      p2a: `Tăng cường <br />âm thanh`,
      p2b: `Trợ lý cuộc gọi`,
      p3a: `Tính năng <br />Volume Plus`,
      p3b: `âm lượng lớn`,
      tips: `*Hình ảnh chỉ mang tính chất minh họa, vui lòng tham khảo mẫu sản phẩm thực tế.<br/>
      *Một số sản phẩm yêu cầu cập nhật hệ thống để trải nghiệm Volume Plus.`,
    },
    sec11: {
      bigTitle: `Tăng gấp đôi, <br />không còn rắc rối!`,
      icon1: {
        top: "-30%",
        left: "-9.8%",
        mobtop: "-30%",
        mobleft: "4%",
      },
      icon2: {
        top: "-31%",
        left: "47%",
        mobtop: "-35%",
        mobleft: "57%",
      },
      icon3: {
        top: "56%",
        left: "86%",
        mobtop: "41%",
        mobleft: "64%",
      },
  
      title: `Dung lượng lớn với  <br class='pc'/> hệ thống tinh gọn`,
      desc: `Không cần đắn do lựa chọn! Với bộ nhớ dung lượng lớn, bạn có thể lưu giữ tất cả những bản nhạc yêu thích và những bức ảnh yêu quý của bạn. Bộ nhớ mở rộng tới 4 GB giúp tăng cường hoạt động liền mạch, với tính năng "Tinh gọn hệ thống" giúp dữ liệu luôn được sắp xếp ngăn nắp và có hệ thống. 
      Không còn tình trạng giật lag. Chỉ còn tốc độ, sự liền mạch và ổn định.`,
      p1a: `Lên tới 1 TB`,
      p1b: `Dung lượng lưu trữ mở rộng`,
      p2a: `Lên tới 8 GB`,
      p2b: `Bộ nhớ tích hợp `,
      p3a: `Tinh gọn hệ thống`,
      p3b: `Dọn dẹp sâu`,
      tips1: `*Gấp đôi RAM (Lên tới 8 GB, RAM mở rộng 4 GB + 4 GB)`,
      tips2: `*Dung lượng lưu trữ mở rộng 1 TB chỉ có trên các mẫu máy có thẻ MicroSD 1 TB. Dung lượng lưu trữ thực tế khả dụng có thể khác nhau tùy theo phần mềm được cài đặt sẵn.`,
      tips3: `*Thẻ MicroSD phải được mua riêng và không được bao gồm trong sản phẩm này.`,
      tips4: `*Hình ảnh chỉ mang tính chất minh họa, vui lòng tham khảo mẫu sản phẩm thực tế.`,
    },
    sec12: {
      bigTitle: `Gấp đôi <br /> năng lượng!`,
      icon1: {
        top: "7%",
        left: "40%",
        mobtop: "56%",
        mobleft: "67%",
      },
      icon2: {
        top: "-35%",
        left: "27%",
        mobtop: "-55%",
        mobleft: "38%",
      },
      icon3: {
        top: "7%",
        left: "63%",
        mobtop: "-1%",
        mobleft: "72%",
      },
  
      title: `Pin lớn 5.000 mAh <br class='pc'/> với cổng  <br class='pc'/> sạc Type-C`,
      desc: `Không còn lo lắng điện thoại sập nguồn với pin công suất lớn siêu bền bỉ trong hơn 900 giờ ở chế độ chờ! Đắm chìm trong video và âm nhạc bất tận. Cổng Type-C đa năng linh hoạt – cắm theo hướng bất kỳ, tùy ý bạn. Một tính năng thường dành riêng cho các dòng sản phẩm cao cấp hơn, giúp nâng cao trải nghiệm của bạn, đồng thời giảm chi phí!`,
      p1a: `5.000 mAh`,
      p1b: `Pin công suất lớn`,
      p2a: `10 W`,
      p2b: `Sạc`,
      p3a: `Type-C `,
      p3b: `Giao diện`,
      tips: `*Hình ảnh chỉ mang tính chất minh họa, vui lòng tham khảo mẫu sản phẩm thực tế.<br/>
      *Được chứng minh bằng dữ liệu từ TECNO LAB`,
    },
    sec13: {
      bigTitle: `Đơn giản hóa cuộc sống,<br />Mở ra thế giới <br /> thông minh`,
      icon1: {
        top: "-15%",
        left: "-14%",
        mobtop: "-15%",
        mobleft: "1%",
      },
      icon2: {
        top: "-3%",
        left: "85%",
        mobtop: "-8%",
        mobleft: "82%",
      },
      icon3: {
        top: "-2%",
        left: "-12%",
        mobtop: "-9%",
        mobleft: "1%",
      },
  
      title: `Mở khóa vân tay cạnh bên`,
      desc: `Dẫn đầu dòng sản phẩm với công nghệ cảm biến vân tay gắn cạnh bên mới nhất. Mở khóa dễ dàng và nhẹ nhàng. Không cần nhấc lên hay nhấn mạnh. Chỉ cần chạm nhẹ bằng đầu ngón tay là thiết bị đã sẵn sàng. `,
      p1a: `Tính theo mili giây`,
      p1b: `Tốc độ mở khóa`,
      p2a: `Khoảng 10mm²`,
      p2b: `Vùng cảm biến rộng`,
      tips: `*Được chứng minh bằng dữ liệu từ TECNO LAB`,
    },
    sec14: {
      bigTitle: `Chạy đua <br /> với tốc độ mili giây <br /> trên Duo Drive.`,
      icon1: {
        top: "0%",
        left: "-15%",
        mobtop: "0%",
        mobleft: "4%",
      },
      icon2: {
        top: "-17%",
        left: "40.5%",
        mobtop: "-17%",
        mobleft: "51.5%",
      },
      icon3: {
        top: "35%",
        left: "70%",
        mobtop: "35%",
        mobleft: "80%",
      },
  
      title: `Bộ xử lý tám nhân`,
      desc: `Với sức mạnh của bộ xử lý Arm Cortex-A53 tám nhân, cung cấp xung nhịp tối đa lên tới 1,6 GHz để mang lại trải nghiệm di động nhanh như chớp! Đạt hơn 170.000 điểm tổng trong thử nghiệm AN TUTU. Công cụ Darwin tự phát triển giúp thiết bị luôn mát để bạn có thể thư giãn khi sử dụng trong thời gian dài. 
      Tận hưởng hiệu suất không bị gián đoạn, mượt mà mà không gặp trở ngại nào!`,
      p1a: `1,6 GHz`,
      p1b: `Xung nhịp tối đa`,
      p2a: `Arm Cortex-A53 tám nhân`,
      p2b: `Bộ xử lý`,
      tips: `*Hình ảnh chỉ mang tính chất minh họa, vui lòng tham khảo mẫu sản phẩm thực tế.<br/>
      *Được chứng minh bằng dữ liệu từ TECNO LAB`,
    },
  
  
  
     // type1: 文案+图片   (文案字段: 在sec1Text下面, 图片字段: sec1Type1ImagePc(pc端)、sec1Type1ImageMob(移动端));
    // type2: 文案+小视频 (文案字段: 在sec1Text下面, 小视频字段: sec1Video.pcType2(pc端)、sec1Video.mobType2(移动端), 视频海报图: type2Post(pc端)、type2PostMob(移动端));  
    // type3: 通屏大视频  (大视频字段: sec1Video.pcType3(pc端)、sec1Video.mobType3(移动端), 视频海报图: type3Post(pc端)、type3PostMob(移动端));
    // type4: 通屏大图片(图片字段: sec1Type4ImagePc(pc端)、sec1Type4ImageMob(移动端))
    sec1Type: 'type3',
    sec1Text: {
      title: `All You Want Just Doubled`,
      p1: "Double <span></span> <br/> Speakers",
      p2: "6.6'' 90Hz <br/> Hole Screen",
      p3: "Up to <span>4+4 GB <br/> Extended RAM</span><br/> 128GB+8GB* ",
      p4: "5000mAh <br/> with Type-C",
      tips: "64GB ROM+6GB RAM*(3GB+3GB Extended) <br/> 64GB ROM+8GB RAM*(4GB+4GB Extended) <br/> 128GB ROM+8GB RAM*(4GB+4GB Extended)",
    },
    sec1Type1ImagePc: 'https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/png/sec1PcBg.png',
    sec1Type1ImageMob: 'https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/png/sec1MobBg.png',
    sec1Video: {
      pcType2: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec1PcSpark.mp4",
      mobType2: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec1PcSpark.mp4",
      pcType3: "https://d3fyizz0b46qgr.cloudfront.net/global/vn/sparkgo2024/sparkgo2024_pc.mp4",
      mobType3: "https://d3fyizz0b46qgr.cloudfront.net/global/vn/sparkgo2024/sparkgo2024_m1.mp4",
      type2Post: "",
      type2PostMob: "",
      type3Post: "",
      type3PostMob: "",
    },
    sec1Type4ImagePc: '',
    sec1Type4ImageMob: '',
    sec6Image: {
      pic1: 'https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/webp/sec7MbF4.webp', //白人
      // pic1: 'https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/png/sec7MbF4_2.png', //黑人
    },
    sec6Video: {
      pc: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec6Pc.mp4",//白人
      // pc: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec6Pc_2.mp4",//黑人
      v1Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec6PcPoster.jpg",
    },
    sec7Video: {
      pc: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec7Pc.mp4",
      mob: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec7Mob.mp4",
      v1Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec7PcPoster.jpg",
      v1PostMob: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec7MobPoster.jpg",
    },
    sec8Video: {
      // 线上
      v1: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec8V1.mp4",
      v1Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec8V1Poster.jpg",
      v2: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec8V2.mp4",
      v2Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec8V2Poster.jpg",
      v3: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec8V3.mp4",
      v3Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec8V3Poster.jpg",
      v4: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec8V4.mp4",
      v4Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec8V4Poster.jpg",
      v5: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec8V5.mp4",
      v5Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec8V5Poster.jpg",
      v6: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec8V6.mp4",
      v6Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec8V6Poster.jpg",
    },
    sec11Video: {
      pc: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec11Pc.mp4",
      v1Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec11PcPoster.jpg",
    },
    sec12Video: {
      pc: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec12Pc.mp4",
      mob: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec12Mob.mp4",
      v1Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec12PcPoster.jpg",
      v1PostMob: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec12MobPoster.jpg",
    },
  }
  
  