window.pop8Config = {
    VITE_FRAMES_URL: 'https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist',
    sec1: {
        icon1Top: "52%",
        icon1Left: "88%",
        icon1MobTop: "52%",
        icon1MobLeft: "83%",
    },
    sec2: {
        t1: `6.6’’ 90Hz Delikli Ekran<br/>Noktalı Ekran`,
        t2: "Minimalist<br/>Kare<br/>Tasarım",
        t3: "Büyük Depolama Alanı ve <span>1TB’</span>a kadar SD Kart ",
        t4: "5000 mAh Büyük Batarya\n" +
            "Type-C",
        t5: "Yan Kenardan \n" +
            "Parmak İzi \n" +
            "Kilit Açma",
        t6: "DTS ile Stereo Çift Hoparlör %400'lük Ses Artışı",
        t7: "Kamera",
    },
    sec3: {
        text: "Estetik",
        title: " Çifte Doku, <br/> İleri Düzeyde <br/> Çekicilik",
        icon1Top: "-7%",
        icon1Left: "-8%",
        icon2Top: "29%",
        icon2Left: "53%",
        icon3Top: "67%",
        icon3Left: "23.6%",
        icon1MobTop: "-7%",
        icon1MobLeft: "-16%",
        icon2MobTop: "29%",
        icon2MobLeft: "85%",
        icon3MobTop: "67%",
        icon3MobLeft: "37.6%",
        t1: "Son Derece Sade Kare Şekil",
        d1: "Şık dokuya ve yepyeni bir tasarıma hazır olun! İnce gövde iki farklı tarzda sunuluyor: Renk cümbüşü Gökkuşağı Halkası ve %100 tehlikesiz yüksek polimerli silikondan üretilen ve birinci sınıf deri hissi veren lüks bir dokuya sahip Magic Skin 2.0! \n" +
            "Görünüşünüzü seçin. Tarzınızı geliştirin!",
        param1t: "8.55 mm",
        param1d: "Ultra İnce",
        param2t: "Kum Taneleri",
        param2d: "Yeni Nesil ",
        param3t: "Milyon Renk ",
        param3d: "Kaplama",
        param4t: "8.75 mm",
        param4d: "Ultra İnce",
        param5t: `Magic<br /> Skin 2.0`,
        param5d: "Deri",
        param6t: `%100 Geri<br /> Dönüştürülebilir`,
        param6d: `Arka Kapak`,
        param7t: `Sıfır`,
        param7d: `Zararlı <br /> Madde`,
        tips: "*TECNO LAB tarafından sağlanan verilerle kanıtlanmıştır",
    },
    sec4: {
        title: "Daha Büyük Bir Harikalar Diyarında Sorunsuzca Gezinin.",
        icon1Top: "-18%",
        icon1Left: "-16%",
        icon2Top: "-29%",
        icon2Left: "36%",
        icon3Top: "17%",
        icon3Left: "92%",
        icon4Top: "69%",
        icon4Left: "-15%",
        icon3MobTop: "5%",
        icon3MobLeft: "95%",
        t1: `Noktalı, 6.6 inç 90Hz Ekran`,
        d1: `6,6 inçlik ultra geniş ekran ile devasa bir harikalar diyarı keşfedin! Sınıfında nadir görülen %90,5'lik muazzam ekran - gövde oranı ile sınırsız bir görsel şölen denizinde geziniyormuş gibi hissedin! Ultra hassas etkileşim sağlayan 90 Hz'lik yüksek yenileme oranı ile benzersiz bir macera olacak!
Her dokunuşta sürprizler sizi bekliyor.`,
        param1t: `Noktalı 6,6 inç `,
        param1d: "Geniş Ekran",
        param2t: "90 Hz",
        param2d: "Yenileme Oranları",
        param3t: "8 H",
        param3d: "Yüzey Sertliği",
        tips: "*TECNO LAB tarafından sağlanan verilerle kanıtlanmıştır",
    },
    sec5: {
        title: "Güzellik ve Çok Yönlülük<br/>Her İki Dünyanın Avantajları",
        icon1Top: "14%",
        icon1Left: "-12%",
        icon2Top: "-53%",
        icon2Left: "65%",
        icon3Top: "74%",
        icon3Left: "28.5%",
        icon4Top: "69%",
        icon4Left: "80%",
        icon1MobTop: "-23%",
        icon1MobLeft: "-21%",
        icon2MobTop: "-28%",
        icon2MobLeft: "89%",
        icon3MobTop: "59%",
        icon3MobLeft: "38%",
        icon4MobTop: "33%",
        icon4MobLeft: "70%",
        t1: "Özel Geliştirilmiş Dinamik Ada",
        d1: `Ekrana sorunsuz şekilde entegre edilen TECNO'nun muhteşem Dinamik Ada’ya hoş geldiniz. Kullanışlı kullanıcı arayüzü etkin bildirimler sağlar; sürekli kilit açmakla, kontrol etmekle veya uygulama değiştirmekle uğraşmadan durumdan haberdar olun. Size esneklik sağlamak adına klasik mod da kullanılabilir. 
Hiçbir şeyden ödün vermeden deneyim sadeleştirildi!`,
    },
    sec6: {
        text: "Görüntü",
        title: "Ön ve Arka<br/>Her İki Tarafta<br/> Netlik",
        icon1Top: "55%",
        icon1Left: "-13.7%",
        icon2Top: "-26%",
        icon2Left: "26%",
        icon3Top: "55%",
        icon3Left: "28%",
        icon4Top: "-2%",
        icon4Left: "62%",
        icon1MobTop: "55%",
        icon1MobLeft: "-13.7%",
        icon2MobTop: "-26%",
        icon2MobLeft: "26%",
        icon3MobTop: "55%",
        icon3MobLeft: "28%",
        icon4MobTop: "-14%",
        icon4MobLeft: "85%",
        t1: "8 MP Çift Flaş ile Selfie",
        d1: "Gün doğumu veya gün batımı, kapalı veya açık alanda, ön taraftaki usta her zaman istediğinizi vermeye hazır! Harika netlik için 8 MP kamera, ışığa duyarlı piksel, çift flaş ve ışıltınız için ekranı dolduran ışık. Ayrıca her cilt rengi için kendini kanıtlamış güzellik geliştirmeleri! \n" +
            "Spot ışığına adım atın ve içinizdeki yıldızın iki kat parlamasını sağlayın.",
        param1t: "Süper Gece",
        param1d: "Algoritma",
        param2t: "8MP",
        param2d: "Ultra Net Selfie",
        param3t: "1.12μm",
        param3d: "Ultra Geniş Piksel Birimi",
        param4t: "Çift Flaş",
        param4d: "Doğal Aydınlatma",
        tips: "*Görseller gösterim amaçlıdır. Lütfen gerçek görüntüyü kontrol edin.",
    },
    sec7: {
        t1: "13 MP HDR Portre Kamera",
        d1: "Süper Geniş açıklık ve Süper Geniş piksel birimi. \n" +
            "Arkadaki SUPER DUO ile portre çekimleriniz her türlü ışıkta inanılmaz düzeyde güzelleşecek. Arka plan ışıklı olsa bile kısılmaz! Netliğin ortaya çıkması için HDR kareleri birleştirir, arka planda oluşturulan bulanıklık ise yıldız gibi ortaya çıkmanızı sağlar. \n" +
            "İstediğiniz zaman istediğiniz yerde güzelliği yakalayın.",
        param1t: "13 MP",
        param1d: "Ultra Net",
        param2t: "HDR Efekti",
        param2d: "Çoklu kare Birleştirme",
        param3t: "F 1.8",
        param3d: "Geniş Açıklık",
        param4t: "1.12 μm",
        param4d: "Ultra Geniş Piksel Birimi",
        tips: "*Görseller gösterim amaçlıdır. Lütfen gerçek görüntüyü kontrol edin.",
    },
    sec8: {
        title: "Gözler Sizin ÜZERİNİZDE!",
        icon1Top: "-21%",
        icon1Left: "-8%",
        icon2Top: "-41%",
        icon2Left: "23%",
        icon3Top: "2%",
        icon3Left: "-8%",
        icon1MobTop: "-21%",
        icon1MobLeft: "-12%",
        icon2MobTop: "-41%",
        icon2MobLeft: "34%",
        icon3MobTop: "-21%",
        icon3MobLeft: "-21%",
        t1: "AR Çekim",
        d1: "Eğlenceli çizgi roman avatalar, canlı arka planlar ve birbirinden farklı AR (Artırılmış Gerçeklik) öğesi ile renkli kişiliğinizi ortaya koyun. \n" +
            "Öne çıkın ve gösterinin yıldızı siz olun!",
        tips: "*Görseller gösterim amaçlıdır. Lütfen gerçek görüntüyü kontrol edin.",
    },
    sec9: {
        title: "Performans",
    },
    sec10: {
        bigTitle: `İki Kat Ritim, İki Kattan Fazla Keyif!`,
        icon1: {
            top: "-26%",
            left: "-9%",
            mobtop: "-34%",
            mobleft: "3%",
        },
        icon2: {
            top: "-57%",
            left: "58%",
            mobtop: "-36%",
            mobleft: "68%",
        },
        icon3: {
            top: "74%",
            left: "-8%",
            mobtop: "49%",
            mobleft: "7%",
        },
        icon4: {
            top: "-9%",
            left: "86%",
            mobtop: "-2%",
            mobleft: "83%",
        },

        title: `Stereo Çift Hoparlör<br>%400 Ses Güçlendirme`,
        desc: `Çift hoparlör ile mobil ses deneyiminizi sinema seviyesine yükseltin! Müzik dinlerken veya video izlerken canlı performansın tam ortasında, melodilerin çevrenizde hayat bulduğunu hissedeceksiniz.<br/> Ayrıca iki kat güçlendirilmiş ses ile gürültülü ortamlarda kristal netliğinde görüşme yapmanın keyfini çıkarın. Hak ettiğiniz lüks ses sistemini keyifle kullanın`,
        p1a: `Stereo Çift<br /> Hoparlör`,
        p1b: `Yüksek Ses Güçlendirme`,
        p2a: `Ses <br />Güçlendirici`,
        p2b: `Arama Asistanı`,
        p3a: `Volume <br>Plus `,
        p3b: `Yüksek Ses`,
        tips: `*Görseller gösterim amaçlıdır. Lütfen gerçek görüntüyü kontrol edin.<br/>*Bazı ürünlerin Volume Plus’ı desteklemesi için sistem güncellemesi gereklidir.`,
    },
    sec11: {
        bigTitle: `Sorun Yok,<br />İki Katı Var!`,
        icon1: {
            top: "-30%",
            left: "-9.8%",
            mobtop: "-30%",
            mobleft: "4%",
        },
        icon2: {
            top: "-31%",
            left: "47%",
            mobtop: "-35%",
            mobleft: "57%",
        },
        icon3: {
            top: "56%",
            left: "57%",
            mobtop: "41%",
            mobleft: "64%",
        },

        title: `Sistem İnceltme ile Daha Geniş<br class='pc'/>Depolama Alanı`,
        desc: `Artık ödün vermek yok! Geniş bellek ile artık en sevdiğiniz müzikleri ve fotoğraflarınızı silmeniz gerekmeyecek. 4 GB'a kadar genişletilmiş bellek sorunsuz çalışmayı güçlendirirken Sistem İnceltme temiz ve rahat şekilde çalışmaya devam etmesini sağlar. 
Gecikme artık geçmişte kaldı. Sadece hız, sorunsuz çalışma ve kararlılık var.`,
        p1a: `1 TB'a kadar`,
        p1b: `Genişletilmiş Depolama Alanı`,
        p2a: `8 GB'a kadar`,
        p2b: `Fusion Bellek `,
        p3a: `Sistem İnceltme`,
        p3b: `Ayrıntılı Temizleme`,
        tips1: `*İki Kat RAM（8GB'a kadar, 4GB + 4GB Genişletilmiş RAM）`,
        tips2: `*1 TB genişletilmiş depolama alanı sadece 1 TB MicroSD kartlı modellerde mevcuttur. Gerçek depolama alanı önceden yüklü yazılıma göre değişiklik gösterebilir.`,
        tips3: `*MicroSD kart ayrıca satın alınmalıdır ve bu ürüne dahil değildir.`,
        tips4: `*Görseller gösterim amaçlıdır. Lütfen gerçek görüntüyü kontrol edin.`,
    },
    sec12: {
        bigTitle: `İki Kat Güce<br> Sahip Olun!`,
        icon1: {
            top: "7%",
            left: "63%",
            mobtop: "56%",
            mobleft: "67%",
        },
        icon2: {
            top: "-35%",
            left: "27%",
            mobtop: "-55%",
            mobleft: "38%",
        },
        icon3: {
            top: "7%",
            left: "63%",
            mobtop: "-1%",
            mobleft: "72%",
        },

        title: `Type-C ile<br> 5000 mAh Büyük Batarya`,
        desc: `Yorulmaz mega pil ile pilinizin sizi yarı yolda bırakacağı endişesinden kurtulun! Kesintisiz videoların ve müziğin keyfini çıkaın. Çok yönlü Type-C bağlantı noktası size ayak uydurur, istediğiniz gibi şarj edin. Genellikle daha yüksek fiyatlı modellere özgü olan bu özellik ile daha düşük maliyetle daha güçlü bir deneyim yaşayın!`,
        p1a: `5000 mAh`,
        p1b: `Büyük Batarya`,
        p2a: `10 W`,
        p2b: `Hızlı Şarj`,
        p3a: `Type-C`,
        p3b: `Arayüz`,
        tips: `*Görseller gösterim amaçlıdır. Lütfen gerçek görüntüyü kontrol edin. <br />
    *Evidenced by data from TECNO LAB`,
    },
    sec13: {
        bigTitle: `Daha Az Çaba ile,<br />Tek Dokunuşla Akıllı Dünyaya<br /> Açılan Kapı`,
        icon1: {
            top: "-15%",
            left: "-14%",
            mobtop: "-15%",
            mobleft: "1%",
        },
        icon2: {
            top: "-3%",
            left: "85%",
            mobtop: "-8%",
            mobleft: "82%",
        },
        icon3: {
            top: "-2%",
            left: "-12%",
            mobtop: "-9%",
            mobleft: "1%",
        },

        title: `Yan Kenardan Parmak İzi 
İle Kilit Açma`,
        desc: `Yan kenarda bulunan öncü parmak izi sensörü ile sınıfının en önemli ürünü. Rahat ve zarif şekilde kilit açın. Telefonu kaldırmak veya uğraşmak yok. Parmak ucunuzla hafifçe dokunun ve cihazınız kullanılmaya hazır. `,
        p1a: `Milisaniye Seviyesinde`,
        p1b: `Kilit Açma Hızı`,
        p2a: `Yaklaşık 10m㎡`,
        p2b: `Büyük Sensör Alanı`,
        tips: `*TECNO LAB tarafından sağlanan verilerle kanıtlanmıştır`,
    },
    sec14: {
        bigTitle: `Duo Drive Milisaniyeler İçinde Çalışır.`,
        icon1: {
            top: "0%",
            left: "-15%",
            mobtop: "0%",
            mobleft: "4%",
        },
        icon2: {
            top: "-17%",
            left: "40.5%",
            mobtop: "-17%",
            mobleft: "51.5%",
        },
        icon3: {
            top: "35%",
            left: "70%",
            mobtop: "35%",
            mobleft: "80%",
        },

        title: `Sekiz Çekirdekli İşlemci`,
        desc: `Şimşek hızında mobil deneyim için pik frekansta 2,2 GHz'e varan hız sağlayan sekiz çekirdekli Arm Cortex-A53 işlemci ile güçlendirildi! Özel olarak geliştirilen Darwin Engine cihazınızı serin tutar, böylece uzun süre kullandığınızda ısınma sorunu yaşamazsınız. 
Teklemeden, kesintisiz ve sorunsuz performansın keyfini çıkarın!`,
        p1a: `1.6GHz`,
        p1b: `Pik Frekans`,
        p2a: `Sekiz çekirdekli Arm Cortex-A53`,
        p2b: `İşlemci`,
        tips: `*Görseller gösterim amaçlıdır. Lütfen gerçek görüntüyü kontrol edin. <br />
    *TECNO LAB tarafından sağlanan verilerle kanıtlanmıştır`,
    },



    // type1: 文案+图片   (文案字段: 在sec1Text下面, 图片字段: sec1Type1ImagePc(pc端)、sec1Type1ImageMob(移动端));
    // type2: 文案+小视频 (文案字段: 在sec1Text下面, 小视频字段: sec1Video.pcType2(pc端)、sec1Video.mobType2(移动端), 视频海报图: type2Post(pc端)、type2PostMob(移动端));
    // type3: 通屏大视频  (大视频字段: sec1Video.pcType3(pc端)、sec1Video.mobType3(移动端), 视频海报图: type3Post(pc端)、type3PostMob(移动端));
    // type4: 通屏大图片(图片字段: sec1Type4ImagePc(pc端)、sec1Type4ImageMob(移动端))
    sec1Type: 'type4',
    sec1Text: {
        title: `İkiye Katla<br>Seviye Atla`,
        p1: "Stereo Çift <span></span> <br/> Hoparlör",
        p2: "6.6'' 90Hz <br/>Noktalı Ekran",
        p3: "8+8 <span>Artırılabilir RAM</span><br/>128GB+8GB",
        p4: "5000 mAh <br/> Type-C",
        tips: "64 GB Depolama + 6 GB RAM (3 GB+3 GB Artırılabilir)<br>64 GB Depolama + 8 GB RAM (4 GB+4 GB Artırılabilir)<br>128 GB Depolama + 8 GB RAM (4 GB+4 GB Artırılabilir)",
    },
    sec1Type1ImagePc: 'https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/png/sec1PcBg.png',
    sec1Type1ImageMob: 'https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/png/sec1MobBg.png',
    sec1Video: {
        pcType2: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec1PcSpark.mp4",
        mobType2: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec1PcSpark.mp4",
        pcType3: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec1PcSparkFull.mp4",
        mobType3: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec1MobSparkFull.mp4",
        type2Post: "",
        type2PostMob: "",
        type3Post: "",
        type3PostMob: "",
    },
    sec1Type4ImagePc: 'https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/bd/Spark%20Go%202024%20Detials%20Page%20Banner%20Desktop.jpg',
    sec1Type4ImageMob: 'https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/bd/Spark%20Go%202024%20Detials%20Page%20Banner%20Mobile.jpg',
    sec6Image: {
        pic1: 'https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/webp/sec7MbF4.webp', //白人
        // pic1: 'https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/png/sec7MbF4_2.png', //黑人
    },
    sec6Video: {
        pc: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec6Pc.mp4",//白人
        // pc: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec6Pc_2.mp4",//黑人
        v1Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec6PcPoster.jpg",
    },
    sec7Video: {
        pc: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec7Pc.mp4",
        mob: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec7Mob.mp4",
        v1Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec7PcPoster.jpg",
        v1PostMob: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec7MobPoster.jpg",
    },
    sec8Video: {
        // 线上
        v1: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec8V1.mp4",
        v1Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec8V1Poster.jpg",
        v2: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec8V2.mp4",
        v2Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec8V2Poster.jpg",
        v3: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec8V3.mp4",
        v3Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec8V3Poster.jpg",
        v4: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec8V4.mp4",
        v4Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec8V4Poster.jpg",
        v5: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec8V5.mp4",
        v5Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec8V5Poster.jpg",
        v6: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec8V6.mp4",
        v6Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec8V6Poster.jpg",
    },
    sec11Video: {
        pc: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec11Pc.mp4",
        v1Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec11PcPoster.jpg",
    },
    sec12Video: {
        pc: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec12Pc.mp4",
        mob: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/video/sec12Mob.mp4",
        v1Post: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec12PcPoster.jpg",
        v1PostMob: "https://d3fyizz0b46qgr.cloudfront.net/global/SPARK_Go_2024/dist/jpg/sec12MobPoster.jpg",
    },
}

