window.S25Config = {
  sec1: {
    bigTitle: `Layar <br class="mb"/> AMOLED <br class="mb"/> Super Cerah`,
    watch: `Smart Watch <br class="mb"/> Storm Ultra`,
    titlea: `AMOLED 6,78"`,
    desca: `Tampilan Super  <br class="pc"/> Cerah`,
    titleb: `32MP`,
    descb: `Kamera <br class='pc' /> Swafoto`,
    titlec: `128GB+16GB*`,
    descc: `(8+8GB) <br class='pc'/> RAM Diperluas`,
    titled: `6.78"`,
    descd: `Super Bright <br /> AMOLED Display`,
    titlee: `2.02"`,
    desce: `Tested <br class='pc'/> Scratchproof Screen`,
    titlef: `iPulse*`,
    descf: `Werns App <br class='pc'/> Pre-installed on S25 Series`,
  },
  sec2: {
    f1: `Menggabungkan teknologi canggih dengan <br class="mb"/> <br class="pc"/> konsep estetika yang mengagumkan`,
    f2: `Elegance in Excellence`,
    f3: `ini adalah merek S25 baru  <br /> dirancang sepenuh hati untuk Anda yang tidak kenal kompromi`,
    scale: `1.4`,
  },
  sec3: {
    f1a: `Super Cerah 6,78"`,
    f1b: `Layar AMOLED`,
    f2a: `hingga`,
    f2b: `16(8+8)GB `,
    f2c: `RAM*`,
    f2d: `+128GB `,
    f2f: `ROM`,
    f2g: `RAM hingga 16 (8+8) GB + ROM 128 GB`,
    f3: `Kelancaran 60 bulan*`,
    f4a: `32MP`,
    f4b: `Kamera Swafoto AI`,
    f5a: `7.3mm`,
    f5b: `Bodi Ultra Ramping`,
    f6a: `Kontrol `,
    f6b: `Inframerah Remote Kontrol`,
    f7a: `IP54`,
    f7b: `Tahan Debu & Air`,
    f8a: `Baru`,
    f8b: `OS 14.5 itel `,
    f9a: `Dapat ditingkatkan ke`,
    f9b: `Android 15™`,
  },
  sec4: {
    titlea: `KEUNGGULAN DALAM`,
    titleb: `TAMPILAN`,
    desc: `Kualitas tampilan tingkat atas, kecerahan terbaik, perawatan mata yang luar biasa, dan ketahanan semuanya dalam satu layar. Keuntungan yang tidak terhingga tercakup dalam tampilan ini.`,
  },
  sec5: {
    title: `Tampilan yang indah <br  class="mb"/> terlihat hidup`,
    desc: `Layar datar kelas atas, yang menampilkan bahan luminesens canggih, menawarkan kecerahan yang luar biasa, kualitas tampilan yang unggul, dan fitur perawatan mata, menampilkan kinerja yang sangat baik dalam setiap aspek.`,
    f1a: `120Hz`,
    f1b: `Laju Penyegaran`,
    f2a: `92%*`,
    f2b: `Rasio Layar-terhadap-bodi`,
    f3a: `5,000,000: 1`,
    f3b: `Rasio Kontras`,
    f4a: `100%`,
    f4b: `Gamut Warna DCI-P3`,
    f5a: `1.07 Miliar`,
    f5b: `Warna`,
    f6a: `1800nit`,
    f6b: `Kecerahan Puncak`,
    f7a: `2.160 Hz`,
    f7b: `Peredupan PWM`,
    f8a: `1.500 Hz`,
    f8b: `Pengambilan Sampel Sentuhan Instan`,
    f9a: `2436*1080`,
    f9b: `Resolusi FHD+`,
  },
  sec6: {
    title: `Terlihat di bawah sinar matahari`,
    desc: `Kecerahan global mencapai 1.200 nit yang mengagumkan, dengan nilai puncak yang sangat tinggi pada 1.800 nit, yang memungkinkan Anda untuk mendapatkan konten yang menarik secara jelas di layar bahkan ketika di bawah sinar matahari langsung.*`,
  },
  sec7: {
    titlea: `Tampilan Sentuhan <br class='pc'/>Basah`,
    desca: `Mendukung tangan basah`,
    titleb: `Pemindai <br />Sidik Jari <br class='pc'/>di Tampilan`,
    descb: `Cepat dan aman`,
  },
  sec8: {
    titlea: `KEUNGGULAN DALAM `,
    titleb: `ESTETIKA`,
    desc: `Gambar inspirasi dari keajaiban alam, dengan estetika dan proses tingkat lanjut, mengubah S25 menjadi item yang trendi! `,
  },
  sec9: {
    title: `Sangat ramping`,
    desc: `Hanya 185 g & Hanya 7,3 mm*`,
  },
  sec10: {
    titlea: `Kreasi yang modis`,
    desca: `Mode di satu sisi, teknologi di sisi lain. Dengan menggabungkan inspirasi alami dengan konsep desain yang canggih, Proses Lapisan Optik tingkat lanjut menciptakan dua tekstur dari gurun dan daun mint, yang menonjolkan kesan premium.`,
    colora: `Gemerlap Sahara`,
    infoa: `Terinspirasi dari pasir keemasan Gurun Sahara, ini terlihat seperti pemandangan indah Sahara yang berkilauan di bawah sinar matahari.`,
    colorb: `Mint Mambo`,
    infob: `Terinspirasi dari hijau mint yang populer, segar dan indah, digabungkan dengan keanggunan langkah tarian mambo, ini terlihat seperti gaya hidup orang muda yang mengejar mode dan mencintai kehidupan.`,
    titleb: `Hitam dengan kejutan `,
    descb: `Desain minimalis, hitam yang tak lekang oleh waktu, sentuhan legap yang nyaman, tampilan klasik yang tak pernah pudar.`,
    colorc: `Hitam Bromo`,
    infoc: `Terinspirasi oleh basal Gunung Bromo di Indonesia, desain ini memancarkan kilau unik basal di bawah sinar matahari, yang menyerupai bintang yang berkelip di langit malam.`,
  },
  sec11: {
    title: `Sinkronkan dengan suasana kamu`,
    desc: `Lampu Cincin LED`,
    info: `Lampu cincin LED tidak hanya menyediakan informasi status yang berbeda melalui efek pencahayaannya, tetapi juga menyajikan tambahan yang modis ke ponsel pintar, membuatnya menarik secara visual dan praktis.`,
    f1: `Pengisian Daya `,
    f2: `Notifikasi`,
    f3: `Bermain Game`,
  },
  sec12: {
    title: `Teman yang  <br />Handal`,
    desc: `Dengan peringkat IP54 untuk ketahanan terhadap debu dan air, perangkat ini terlindungi baik terhadap pemakaian dan keausan sehari-hari, termasuk rembesan debu dan percikan air ringan.`,
  },
  sec13: {
    titlea: `KEUNGGULAN DALAM`,
    titleb: `KINERJA`,
    desc: `Peningkatan kinerja yang luar biasa, digabungkan dengan penyesuaian perangkat lunak yang efektif, pengalaman "ponsel baru" untuk banyak tahun.`,
  },
  sec14: {
    title: `60 bulan penggunaan yang lancar`,
    desc: `Setelah melewati pengujian yang ketat di lab itel, ponsel ini dijamin bebas lambat selama 5 tahun, berkat Teknologi Ekspansi Memori Virtual dan Teknologi Penyimpanan Atom, Anda tidak perlu khawatir lagi tentang melemahnya kinerja ponsel seiring waktu.`,
    f1a: `hingga`,
    f1b: `16(8+8)GB RAM`,
    f1c: `18 Aplikasi yang berjalan secara bersamaan.*`,
    f2a: `hingga`,
    f2b: `128GB ROM`,
    f2c: `Mampu menyimpan 30.000+ foto.*`,
  },
  sec15: {
    title: `Bebaskan sang monster`,
    desc: `S25 dilengkapi dengan prosesor octa-core yang mumpuni dengan ARM Cortex-A75 hingga 2,2 Ghz, yang digabungkan dengan sistem pendinginan Grafit, untuk membebaskan kinerjanya secara penuh dan memungkinkan Anda menikmati game seluler arus utama dengan mudah.`,
  },
  sec16: {
    title: `Kemampuan penetrasi <br class="mb"/> dinding super`,
    desc: `S25 mendukung Wi-Fi Super, yang menyediakan latensi ultrarendah untuk bermain game yang lancar dan secara otomatis beralih ke jaringan terbaik lintas jaringan Wi-Fi yang berbeda, yang menawarkan kekuatan sinyal yang lebih kuat secara signifikan di ruang publik dengan Wi-Fi bersama.`,
    f1a: `6,5 MB/dtk`,
    f1b: `Kecepatan pengunduhan ketika<br/>  menggunakan Wi-Fi dan Bluetooth bersama-sama `,
    f2a: `26 mdtk*`,
    f2b: `Latensi super rendah <br /> untuk bermain game`,
    f3a: `5x`,
    f3b: `Pengalihan yang lebih cepat  <br /> ke jaringan Wi-Fi yang optimal`,
  },
  sec17: {
    titlea: `Pembangkit tenaga <br class="mb"/> di tangan Anda`,
    desca: `S25 disertai dengan baterai 5.000 mAh yang sangat besar dan pengisian daya supercepat sebesar 18 W. `,
    titleb: `Tidak ada kompromi dalam bermain game`,
    descb: `Ponsel dengan Teknologi Pengisian Daya Bypass dapat diberi daya secara langsung tanpa melewati baterai, memastikan pengalaman bermain game atau menonton yang bebas panas saat mengisi daya secara bersamaan.*`,
  },
  sec18: {
    titlea: `KEUNGGULAN DALAM`,
    titleb: `FOTOGRAFI`,
    desc: `Kamera depan dan belakang ultrajernih,dengan fitur dan filter yang dibuat secara khusus,mengubah semua orang menjadi master fotografi.`,
  },
  sec19: {
    f1a: `32MP`,
    f1b: `Kamera Swafoto AI `,
    f1c: `FOV: 88.9° `,
    f1d: `Apertur: f/2.2`,
    f2a: `50MP`,
    f2b: `Kamera Ultrajernih`,
    f2c: `Ukuran piksel: 0.64μm `,
    f2d: `Apertur: f/1.6`,
  },
  sec20: {
    title: `Keindahan dalam fokus`,
    desc: `Kamera Swafoto AI 32 MP terkemuka dengan sudut besar, yang menyediakan Kecantikan AI 2.0, menangkap swafoto yang mengagumkan dengan detail dan kejernihan yang luar biasa, bahkan dalam foto grup.`,
    tipsa: `Mendukung Rana`,
    tipsb: `Kontrol Suara`,
    tipsc: `Mendukung `,
    tipsd: `Rana Senyum`,
  },
  sec21: {
    title: `Kejelasan di setiap detail`,
    subTitlea: `Mode 50 MP`,
    infoa: `Kamera Ultrajernih 50 MP terbaik di kelasnya memungkinkan Anda dengan mudah menangkap foto yang jernih dan menawan dalam setiap lingkungan yang kompleks, mulai dari skenario pencahayaan rendah hingga cahaya latar. Bahkan, Anda dapat menangkap momen sorotan Anda dengan merekam dalam video 2K!`,
    subTitleb: `Mode Super Malam`,
    off: `Mati`,
    on: `Hidup`,
    hdr: `HDR Super`,
  },
  sec22: {
    title: `Memotret dengan bakat`,
    desc: `Berani mengintegrasikan teknologi AI ke dalam fotografi seluler, menciptakan tiga filter warna kulit dengan gaya khas yang memungkinkan foto Anda menyampaikan berbagai emosi dan atmosfer dengan mudah. Digabungkan dengan penggunaan tanda air master yang eksklusif, setiap foto yang Anda ambil diubah menjadi mahakarya dengan sekejap.`,
    f1: `Standar`,
    f2: `Cerah`,
    f3: `Master`,
  },
  sec23: {
    title: `Memotret dengan seru`,
    desc: `Nikmati keseruan merekam vlog dengan Perekaman Video Tampilan Ganda, yang secara mudah menangkap reaksi Anda dan pemandangan indah yang Anda nikmati, atau interaksi keterlibatan dengan teman Anda.`,
  },
  sec24: {
    titlea: `KEUNGGULAN DALAM`,
    titleb: `PENGALAMAN`,
    desc: `Setiap fitur disempurnakan secara teliti,dengan pembaruan dan pengoptimalan terus-menerus,memastikannya selalu ramah pengguna.`,
  },
  sec25: {
    title: `OS 14.5 itel Baru`,
    desc: `Dengan didasarkan pada Android 14 terbaru, sistem ini memperkenalkan desain UI yang lebih modis dan fungsionalitas widget desktop yang disempurnakan, memberi Anda pengalaman sistem yang menyenangkan secara estetika dan lancar.`,
  },
  sec26: {
    android: {
      title: `Dapat ditingkatkan ke  <br class='mb' /> Android 15™`,
      desc: `Dukungan selama 2 tahun sistem Android dan peningkatan patch keamanan yang secara signifikan memperpanjang masa pakai ponsel Anda.`,
    },
    gpt: {
      title: `Asisten AI GPT`,
      desc: `Ucapkan halo pada asisten terbaik Anda! Asisten ini membebaskan tangan Anda dan membantu Anda menangani banyak tugas sederhana.`,
    },
    aiCall: {
      title: `Penghilang Derau <br class='pc'/>Panggilan Telepon AI`,
    },
    aiWallpaper: {
      title: `Wallpaper AI`,
    },
    askAi: {
      title: `ASK AI`,
    },
    dynamicBar: {
      title: `Dynamic Bar`,
      desc: `Selamat datang di Dynamic Bar, yang membuat akses ke notifikasi penting kini lebih praktis dan lancar dibandingkan sebelumnya.`,
    },
    aod: {
      title: `AOD Pintar`,
      desc: `Informasi penting dapat <br class='mb'/> diakses dengan mudah.`,
    },
    infrared: {
      title: `Inframerah <br class='mb'/>Kontrol Jarak Jauh `,
      desc: `Ubah ponsel pintar Anda menjadi <br /> pengontrol serbaguna untuk <br /> peralatan rumah tangga.*`,
    },
    nfc: {
      title: `NFC`,
      desc: `Tak perlu membawa <br class='mb'/>  dompet atau<br class='pc'/> kartu transportasi ketika bepergian.*`,
    },
    dts: {
      title: `Suara dari DTS`,
      desc: `Audio DTS memberikan suara <br class='pc'/> fidelitas tinggi dan <br class='pc'/> menghanyutkan ke ponsel pintar <br class='pc'/> Anda untuk pengalaman <br class='pc'/> mendengarkan yang <br class='pc'/> disempurnakan.`,
    },
  },
  sec27: {
    title: `Konektivitas <br class='pc'/> pintar`,
    desc: `Fitur ini terintegrasi dengan Aplikasi iPulse dan mendukung interkoneksi yang lancar dengan jam tangan itel Anda, yang mengizinkan Anda mengontrol fotografi ponsel pintar dari jarak jauh dan menyinkronkan data kesehatan ke ponsel. Ini bukan sekadar tentang Internet of Things, ini melambangkan gaya hidup yang trendi.*`,
  },
  sec28: {
    notes: `Catatan`,
    f1: `1. Data Fluensi 60 bulan diperoleh dari Lab itel. Data aktual dapat bervariasi karena adanya faktor seperti lingkungan pengujian atau metode penghitungan; oleh karena itu, lihat produk aktual.`,
    f2: `2. S25 RAM versi 128 + 16 GB terdiri dari ekspansi (8+8) GB.`,
    f3: `3. Data rasio layar-terhadap-bodi dan kecerahan diperoleh dari Lab itel. Data aktual dapat bervariasi karena adanya faktor seperti lingkungan pengujian atau metode penghitungan; oleh karena itu, lihat produk aktual.`,
    f4: `4. Data berat dan ketebalan diperoleh dari Lab itel. Data aktual dapat bervariasi karena adanya faktor seperti lingkungan pengujian atau metode penghitungan; oleh karena itu, lihat produk aktual.`,
    f5: `5. Data penyimpanan sebesar "30.000+ Foto" diperoleh dari Lab itel. Data aktual dapat bervariasi karena adanya faktor seperti lingkungan pengujian atau metode penghitungan; oleh karena itu, lihat produk aktual.`,
    f6: `6. Data 18 Aplikasi Berjalan Secara Bersamaan berasal dari Lab itel. Data aktual dapat bervariasi karena adanya faktor seperti lingkungan pengujian atau metode penghitungan; oleh karena itu, lihat produk aktual.`,
    f7: `7. Data Wi-Fi Super diperoleh dari Lab itel. Data aktual dapat bervariasi karena adanya faktor seperti lingkungan pengujian atau metode penghitungan; oleh karena itu, lihat produk aktual. `,
    f8: `8. Baterai itel S25 memiliki kapasitas tipikal 5.000 mAh dan kapasitas nominal 4.900 mAh.`,
    // f9: `9. The data of 1000 charge cycles is obtained from the itel Lab. Actual data may vary due to factors such as test environments or calculation <br class='pc'/> methods, so please refer to the actual product.`,
    f10: `9. Data Teknologi Pengisian Daya Bypass diperoleh dari Lab itel. Data aktual dapat bervariasi karena adanya faktor seperti lingkungan pengujian atau metode penghitungan; oleh karena itu, lihat produk aktual. `,
    f11: `10. Android adalah merek dagang dari Google LLC.`,
    f12: `11. Ketersediaan fitur Kontrol Jarak Jauh Inframerah dan NFC dapat bervariasi berdasarkan kawasan dan perangkat. Lihat situasi aktual untuk perinciannya.`,
    f13: `12. iPulse, aplikasi jam tangan milik itel, kompatibel secara luas dan sudah dipasang di itel S25 Series.`,
    f14: `13. Gambar produk hanya untuk referensi, lihat produk aktual. Beberapa spesifikasi dan deskripsi dapat berubah karena penggantian pemasok, lihat produk aktual. Data yang disebutkan didasarkan pada spesifikasi teknis desain kami, laboratorium, dan data pengujian pemasok, serta situasi aktual dapat sedikit bervariasi karena perbedaan versi perangkat lunak pengujian, lingkungan pengujian spesifik, dan versi.`,
  },
  video: {
    sec23: {
      pc: {
        src: "/fileadmin/assets/v/S25/dist/videos/sec23Pc.mp4",
        post: "",
      },
      mob: {
        src: "/fileadmin/assets/v/S25/dist/videos/sec23Pc.mp4",
        post: "",
      },
    },
    sec2: {
      pc: {
        src: "/fileadmin/assets/v/S25/dist/videos/shortPc.mp4",
        post: "",
      },
      mob: {
        src: "/fileadmin/assets/v/S25/dist/videos/shortMb.mp4",
        post: "",
      },
    },
    fullVideo: {
      pc: {
        src: "/fileadmin/assets/v/S25/dist/videos/longPc.mp4",
        post: "",
      },
      mob: {
        src: "/fileadmin/assets/v/S25/dist/videos/longMb.mp4",
        post: "",
      },
    },
  },
}
