window.S25Config = {
  sec1: {
    bigTitle: `Écran AMOLED  <br class="mb"/>ultra-lumineux`,
    watch: `Smart Watch <br class="mb"/> Storm Ultra`,
    titlea: `Écran AMOLED de 6,78'' `,
    desca: `Écran ultra-lumineux`,
    titleb: `32MP `,
    descb: `Appareil photo selfie`,
    titlec: `128Go + 16Go* `,
    descc: `(8+8Go) <br class='pc'/> RAM étendue`,
    titled: `6.78"`,
    descd: `Super Bright <br /> AMOLED Display`,
    titlee: `2.02"`,
    desce: `Tested <br class='pc'/> Scratchproof Screen`,
    titlef: `iPulse*`,
    descf: `Werns App <br class='pc'/> Pre-installed on S25 Series`,
  },
  sec2: {
    f1: `Combinaison de technologies de pointe  <br class="pc"/>  et de concepts esthétiques d'avant-garde`,
    f2: `Elegance in Excellence`,
    f3: `voici le tout nouveau S25  <br /> conçu juste pour vous, plus de compromis`,
    scale: `1.8`,
  },
  sec3: {
    f1a: `ultra-lumineux de 6,78''`,
    f1b: `Écran AMOLED `,
    f2a: `Jusqu'à `,
    f2b: `16(8+8)Go`,
    f2c: `RAM*`,
    f2d: `128Go `,
    f2f: `ROM`,
    f2g: `16(8+8)Go de RAM* + 128Go de ROM`,
    f3: `60 mois de fluidité*`,
    f4a: `32MP`,
    f4b: `Appareil photo selfie AI`,
    f5a: `7.3mm`,
    f5b: `Corps ultra-mince`,
    f6a: `Contrôle `,
    f6b: `infrarouge à distance`,
    f7a: `IP54`,
    f7b: `Résistant à la poussière et à l'eau`,
    f8a: `Tout nouveau `,
    f8b: `itel OS 14.5`,
    f9a: `Possibilité de mettre à jour vers `,
    f9b: `Android 15™`,
  },
  sec4: {
    titlea: `EXCELLENCE EN`,
    titleb: `VISION`,
    desc: `Qualité d'affichage de premier ordre, excellente luminosité, superbe éclairage nocturne et durabilité, le tout dans un seul écran. Cet affichage offre de nombreux avantages.`,
  },
  sec5: {
    title: `Un écran vibrant <br  class="mb"/> prend vie`,
    desc: `Un écran plat de niveau phare, doté de matériaux luminescents de pointe, offre une luminosité étonnante, une excellente qualité d'affichage et des fonctions de protection des yeux et d'excellentes performances dans tous les aspects.`,
    f1a: `120Hz`,
    f1b: `Taux de rafraîchissement`,
    f2a: `92%*`,
    f2b: `Rapport écran-corps`,
    f3a: `5,000,000: 1`,
    f3b: `Rapport de contraste`,
    f4a: `100%`,
    f4b: `Gamme de couleurs DCI-P3`,
    f5a: `1.07 milliard`,
    f5b: `Couleurs`,
    f6a: `1800nits`,
    f6b: `Luminosité maximale`,
    f7a: `2160Hz`,
    f7b: `Gradation PWM`,
    f8a: `1500Hz`,
    f8b: `Échantillonnage tactile instantané`,
    f9a: `2436*1080`,
    f9b: `Résolution FHD+`,
  },
  sec6: {
    title: `Visible à la lumière du soleil`,
    desc: `La luminosité globale atteint un étonnant 1200 nits, avec des valeurs maximales de 1800 nits, vous permettant de percevoir le contenu attrayant sur l'écran, même en plein soleil.*`,
  },
  sec7: {
    titlea: `Écran tactile avec <br class='pc'/>main mouillée`,
    desca: `Prise en charge de l'utilisation avec les mains mouillées`,
    titleb: `Déverrouillage par <br />empreintes digitales <br class='pc'/>intégré à l'écran`,
    descb: `Rapide et sûr`,
  },
  sec8: {
    titlea: `EXCELLENCE EN`,
    titleb: `ESTHÉTIQUE`,
    desc: `S'inspirant des merveilles de la nature, avec l'esthétique et le processus les plus avancés, le S25 se transforme en une pièce élégante! `,
  },
  sec9: {
    title: `Extrêmement mince`,
    desc: `Seulement 185g et 7,3mm*`,
  },
  sec10: {
    titlea: `Une création de style`,
    desca: `D'un côté la mode, de l'autre la technologie. En combinant l'inspiration naturelle avec des concepts de design de pointe, le processus de revêtement optique avancé crée deux textures de désert et de menthe, donnant une impression haut de gamme.`,
    colora: `Lueur du Sahara`,
    infoa: `Inspirée des dunes dorées du désert du Sahara, cette couleur ressemble à une magnifique scène du Sahara scintillant sous le soleil.`,
    colorb: `Menthe Mambo`,
    infob: `Inspirée du vert menthe populaire actuel, cette couleur est fraîche et vibrante, combinée à l'élégance des pas de danse Mambo et est à l'image du style de vie des jeunes qui recherchent la mode et l'amour de la vie.`,
    titleb: `Noir avec une touche d'originalité`,
    descb: `Design simple, noir intemporel, toucher mat confortable, classique inaltérable.`,
    colorc: `Noir de Bromo`,
    infoc: `Inspiré du basalte du mont Bromo en Indonésie, il reflète l'éclat unique du basalte sous la lumière du soleil, ressemblant aux étoiles scintillantes dans le ciel nocturne.`,
  },
  sec11: {
    title: `Synchronisation de votre humeur`,
    desc: `Anneau de lumière LED`,
    info: `L'anneau de lumière LED fournit non seulement différentes informations sur l'état de l'appareil grâce à ses effets de lumière, mais il constitue également un complément élégant aux smartphones, ce qui le rend à la fois attrayant et pratique.`,
    f1: `Charge`,
    f2: `Notifications`,
    f3: `Jeux`,
  },
  sec12: {
    title: `Un compagnon <br />fiable`,
    desc: `Grâce à un indice IP54 pour la résistance à la poussière et à l'eau, ce téléphone est bien protégé contre l'usure quotidienne, qu'il s'agisse d'intrusion de poussière ou de petites éclaboussures d'eau.`,
  },
  sec13: {
    titlea: `EXCELLENCE EN`,
    titleb: `PERFORMANCE`,
    desc: `L'amélioration remarquable des performances, avec un réglage efficace du logiciel, offre une expérience de «nouveau téléphone» pendant de nombreuses années.`,
  },
  sec14: {
    title: `60 mois d'utilisation fluide`,
    desc: `Après des tests rigoureux effectués par le laboratoire itel, ce téléphone est garanti sans décalage pendant 5 ans. Grâce à la puissante technologie d'extension de la mémoire virtuelle et à la technologie de stockage Atom, vous n'avez plus à vous soucier de l'affaiblissement des performances de votre téléphone au fil du temps.`,
    f1a: `Jusqu'à`,
    f1b: `16(8+8)Go de RAM`,
    f1c: `18 applications exécutées simultanément.*`,
    f2a: `Jusqu'à`,
    f2b: `128Go de ROM`,
    f2c: `Capable de stocker plus de 30000 photos.*`,
  },
  sec15: {
    title: `Libérer le potentiel`,
    desc: `Le S25 est doté d'un puissant processeur octa-core avec ARM Cortex-A75 jusqu'à 2,2GHz, associé à un système de refroidissement Graphite, afin d'exploiter pleinement ses performances et de vous permettre de profiter facilement des jeux mobiles grand public.`,
  },
  sec16: {
    title: `Excellente capacité de pénétration des murs`,
    desc: `Doté du Super Wi-Fi, le S25 offre une latence ultra-faible pour des jeux fluides et passe automatiquement au meilleur réseau parmi les différents réseaux Wi-Fi, offrant ainsi une puissance de signal plus forte dans les espaces publics où le Wi-Fi est partagé.`,
    f1a: `6.5MB/s`,
    f1b: `Vitesse de téléchargement <br class='mb'/> simultanée via Wi-Fi et Bluetooth`,
    f2a: `26ms*`,
    f2b: `Très faible latence  <br class='mb'/> pour les jeux`,
    f3a: `5x`,
    f3b: `Passage plus rapide <br class='mb'/> au réseau Wi-Fi optimal`,
  },
  sec17: {
    titlea: `La puissance dans <br class='mb'/> votre main`,
    desca: `Le S25 est doté d'une énorme batterie de 5000mAh et d'une charge super rapide de 18W.  `,
    titleb: `Une expérience de jeu sans compromis`,
    descb: `Grâce à la technologie de charge de contournement, le téléphone peut être alimenté directement sans passer par la batterie, garantissant ainsi une expérience de jeu ou de visionnage sans chaleur tout en chargeant simultanément.*`,
  },
  sec18: {
    titlea: `EXCELLENCE EN`,
    titleb: `PHOTOGRAPHIE`,
    desc: `Des appareils photo avant et arrière ultra-clairs, avec des fonctions et des filtres spécialement conçus, pour rendre chacun maître dans l'art de la photographie.`,
  },
  sec19: {
    f1a: `32MP`,
    f1b: `Appareil photo selfie AI`,
    f1c: `FOV: 88.9° `,
    f1d: `Ouverture: f/2.2`,
    f2a: `50MP`,
    f2b: `Appareil photo ultra-clair `,
    f2c: `Taille du pixel: 0.64μm `,
    f2d: `Ouverture: f/1.6`,
  },
  sec20: {
    title: `La beauté en évidence`,
    desc: `L'appareil photo selfie AI de 32MP de pointe avec grand angle, dotée de la fonction Embellissement AI 2.0, capture des selfies époustouflants avec des détails et une clarté exceptionnels, même sur les photos de groupe.`,
    tipsa: `Avec l'obturateur à `,
    tipsb: `commande vocale`,
    tipsc: `Avec l'obturateur `,
    tipsd: `de sourire`,
  },
  sec21: {
    title: `Clarté dans chaque détail`,
    subTitlea: `Mode 50MP`,
    infoa: `L'appareil photo ultra-clair de 50MP, le meilleur de sa catégorie, vous permet de prendre sans effort des photos claires et époustouflantes dans n'importe quel environnement complexe, qu'il s'agisse de scènes à faible luminosité ou à contre-jour. Et mieux encore, vous pouvez capturer vos meilleurs moments en enregistrant en vidéo 2K!`,
    subTitleb: `Mode Nuit super`,
    off: `Désactivé`,
    on: `Activé`,
    hdr: `Super HDR`,
  },
  sec22: {
    title: `Capturer avec brio`,
    desc: `En intégrant la technologie AI dans la photographie mobile, trois filtres de tonalité de style unique sont créés pour faciliter la transmission d'une variété d'émotions et d'atmosphères dans vos photos. Avec l'utilisation d'un filigrane exclusif, chaque cliché que vous prenez se transforme instantanément en chef-d'œuvre.`,
    f1: `Standard`,
    f2: `Lumineux`,
    f3: `Maître`,
  },
  sec23: {
    title: `Capturer en s'amusant`,
    desc: `Profitez du plaisir du Vlogging grâce à l'enregistrement vidéo double vue pour capturer facilement vos réactions et les paysages époustouflants que vous admirez, ou encore les interactions intéressantes avec vos amis.`,
  },
  sec24: {
    titlea: `EXCELLENCE DANS`,
    titleb: `L'EXPÉRIENCE`,
    desc: `Chaque fonctionnalité est méticuleusement affinée, avec des mises à jour et des optimisations continues,garantissant une utilisation toujours conviviale.`,
  },
  sec25: {
    title: `Tout nouveau itel OS 14.5`,
    desc: `Basé sur la dernière version d'Android 14, il présente une interface utilisateur plus élégante et des fonctionnalités de widget de bureau améliorées, vous offrant une expérience système plus esthétique et plus transparente.`,
  },
  sec26: {
    android: {
      title: `Possibilité de mettre à jour vers  <br class='mb' /> Android 15™`,
      desc: `2 ans de mises à jour et des correctifs de sécurité du système Android prolongent considérablement la durée de vie de votre téléphone.`,
    },
    gpt: {
      title: `Assistant AI GPT`,
      desc: `Dites bonjour à votre meilleur assistant! Il vous libère les mains et vous aide à effectuer de nombreuses tâches simples.`,
    },
    aiCall: {
      title: `Annulation du bruit <br class='pc'/>des appels par AI`,
    },
    aiWallpaper: {
      title: `Fond d'écran AI`,
    },
    askAi: {
      title: `ASK AI`,
    },
    dynamicBar: {
      title: `Dynamic Bar`,
      desc: `Bienvenue à la Dynamic Bar, qui rend désormais l'accès aux notifications cruciales plus pratique et plus transparent que jamais.`,
    },
    aod: {
      title: `AOD intelligent`,
      desc: `Les informations importantes <br class='mb'> sont facilement accessibles.`,
    },
    infrared: {
      title: `Contrôle <br class='mb'/>infrarouge à distance `,
      desc: `Transformez votre smartphone <br class='mb'> en contrôleur <br class='pc'/> polyvalent pour les <br class='mb'> appareils électroménagers.*`,
    },
    nfc: {
      title: `NFC`,
      desc: `Il n'est pas nécessaire de se munir d'un portefeuille ou d'une carte de transport pour sortir.*`,
    },
    dts: {
      title: `Son par DTS`,
      desc: `Le système audio DTS offre un son immersif et de haute fidélité à votre smartphone pour une expérience d'écoute améliorée.`,
    },
  },
  sec27: {
    title: `Connectivité   <br class='pc'/> intelligente`,
    desc: `L'application iPulse intégrée permet une interconnexion transparente avec votre montre itel, facilitant le contrôle à distance de la photographie du smartphone et la synchronisation des données de santé avec le téléphone. Il ne s'agit pas seulement de l'Internet des objets, mais également d'un style de vie à la mode.*`,
  },
  sec28: {
    notes: `Notes`,
    f1: `1. Les données sur la fluidité à 60 mois sont obtenues auprès du laboratoire itel. Les données réelles peuvent varier en raison de facteurs tels que les environnements de test ou les méthodes de calcul, veuillez donc vous référer au produit réel.`,
    f2: `2. La RAM de version 128Go+16Go du S25 est composée d'une extension de (8+8)Go.`,
    f3: `3. Les données relatives au rapport écran-corps et à la luminosité sont obtenues auprès du laboratoire itel. Les données réelles peuvent varier en raison de facteurs tels que les environnements de test ou les méthodes de calcul, veuillez donc vous référer au produit réel.`,
    f4: `4. Les données relatives au poids et à l'épaisseur sont obtenues auprès du laboratoire itel. Les données réelles peuvent varier en raison de facteurs tels que les environnements de test ou les méthodes de calcul, veuillez donc vous référer au produit réel.`,
    f5: `5. Les données de stockage de «plus de 30000 photos» sont obtenues auprès du laboratoire itel. Les données réelles peuvent varier en raison de facteurs tels que les environnements de test ou les méthodes de calcul, veuillez donc vous référer au produit réel.`,
    f6: `6. Les données relatives aux 18 applications exécutées simultanément sont obtenues auprès du laboratoire itel. Les données réelles peuvent varier en raison de facteurs tels que les environnements de test ou les méthodes de calcul, veuillez donc vous référer au produit réel.`,
    f7: `7. Les données de Super Wi-Fi sont obtenues auprès du laboratoire itel. Les données réelles peuvent varier en raison de facteurs tels que les environnements de test ou les méthodes de calcul, veuillez donc vous référer au produit réel. `,
    f8: `8. La batterie de l'itel S25 dispose d'une capacité typique de 5000mAh et d'une capacité nominale de 4900mAh.`,
    // f9: `9. The data of 1000 charge cycles is obtained from the itel Lab. Actual data may vary due to factors such as test environments or calculation <br class='pc'/> methods, so please refer to the actual product.`,
    f10: `9. Les données de la technologie de charge de contournement sont obtenues auprès du laboratoire itel. Les données réelles peuvent varier en raison de facteurs tels que les environnements de test ou les méthodes de calcul, veuillez donc vous référer au produit réel.`,
    f11: `10. Android est une marque déposée de Google LLC.`,
    f12: `11. La disponibilité des fonctions de télécommande infrarouge et NFC peut varier selon la région et l'appareil. Veuillez vous référer à la situation réelle pour plus de détails.`,
    f13: `12. iPulse, l'application de montre d'itel, est largement compatible et préinstallée sur la série S25 d'itel.`,
    f14: `13. Les images du produit sont fournies à titre de référence uniquement, veuillez-vous référer au produit réel. Certaines spécifications et descriptions peuvent varier en raison de remplacements effectués par des fournisseurs, veuillez-vous référer au produit réel. Les données mentionnées sont basées sur les spécifications techniques de nos conceptions, les données de test des laboratoires et des fournisseurs. Les situations réelles peuvent varier légèrement en raison des différentes versions des logiciels de test, des environnements de test et des versions spécifiques.`,
  },
  video: {
    sec23: {
      pc: {
        src: "/fileadmin/assets/v/S25/dist/videos/sec23Pc.mp4",
        post: "",
      },
      mob: {
        src: "/fileadmin/assets/v/S25/dist/videos/sec23Pc.mp4",
        post: "",
      },
    },
    sec2: {
      pc: {
        src: "/fileadmin/assets/v/S25/dist/videos/shortPc.mp4",
        post: "",
      },
      mob: {
        src: "/fileadmin/assets/v/S25/dist/videos/shortMb.mp4",
        post: "",
      },
    },
    fullVideo: {
      pc: {
        src: "/fileadmin/assets/v/S25/dist/videos/longPc.mp4",
        post: "",
      },
      mob: {
        src: "/fileadmin/assets/v/S25/dist/videos/longMb.mp4",
        post: "",
      },
    },
  },
}
