window.S25Config = {
  sec1: {
    bigTitle: `Tela <br class="mb"/> AMOLED <br class="mb"/> com brilho`,
    watch: `Smart Watch <br class="mb"/> Storm Ultra`,
    titlea: `6.78" AMOLED`,
    desca: `Tela Com <br class="pc"/> Brilho`,
    titleb: `32MP`,
    descb: `Câmara <br class='pc' /> para selfies`,
    titlec: `128GB+16GB*`,
    descc: `(8+8GB) <br class='pc'/> RAM expandida`,
    titled: `6.78"`,
    descd: `Super Bright <br /> AMOLED Display`,
    titlee: `2.02"`,
    desce: `Tested <br class='pc'/> Scratchproof Screen`,
    titlef: `iPulse*`,
    descf: `Werns App <br class='pc'/> Pre-installed on S25 Series`,
  },
  sec2: {
    f1: `Combinando tecnologia de ponta com <br class="pc"/>  conceitos estéticos ultra modernos`,
    f2: `Elegance in Excellence`,
    f3: `este é o novíssimo S25  <br /> cuidadosamente concebidos a pensar em si, sem compromissos`,
    scale: `1.8`,
  },
  sec3: {
    f1a: `Tela AMOLED de `,
    f1b: `6,78” Com Brilho`,
    f2a: `Até`,
    f2b: `16(8+8)GB `,
    f2c: `RAM*`,
    f2d: `+128GB `,
    f2f: `ROM`,
    f2g: `16(8+8)GB de RAM*+128GB de ROM`,
    f3: `Fluência a 60 meses*`,
    f4a: `Câmera`,
    f4b: `32MP AI para Selfies`,
    f5a: `7.3mm`,
    f5b: `Corpo Ultrafino`,
    f6a: `Controlo `,
    f6b: `Remoto por Infravermelhos`,
    f7a: `IP54`,
    f7b: `Resistente à Poeira e à Água `,
    f8a: `O Novíssimo`,
    f8b: `itel OS 14.5`,
    f9a: `Atualizável para`,
    f9b: `Android 15™`,
  },
  sec4: {
    titlea: `EXCELÊNCIA NA`,
    titleb: `VISÃO`,
    desc: `Qualidade de tela de topo, brilho de primeira, excelente saúde ocular e durabilidade, tudo numa única tela. Esta tela apresenta inúmeras vantagens.`,
  },
  sec5: {
    title: `Uma tela curva  <br  class="mb"/> vibrante ganha vida`,
    desc: `Uma tela plana de topo de gama, com materiais luminescentes de última geração, oferece um brilho espantoso, uma qualidade de tela superior e características de protecção da vista, apresentando um desempenho excepcional em todos os aspectos.`,
    f1a: `120Hz`,
    f1b: `Taxa de actualização`,
    f2a: `92%*`,
    f2b: `Rácio de tela/corpo`,
    f3a: `5,000,000: 1`,
    f3b: `Rácio de contraste`,
    f4a: `100%`,
    f4b: `Gama de Cores DCI-P3`,
    f5a: `1.07 Biliões`,
    f5b: `Cores`,
    f6a: `1800nits`,
    f6b: `Brilho Máximo`,
    f7a: `2160Hz`,
    f7b: `Escurecimento PWM`,
    f8a: `1500Hz`,
    f8b: `Amostragem por Toque Instantâneo`,
    f9a: `2436*1080`,
    f9b: `Resolução FHD+`,
  },
  sec6: {
    title: `Visível à luz do sol`,
    desc: `A luminosidade global atinge uns espantosos 1200 nits, com valores de pico incrivelmente elevados de 1800 nits, o que lhe permite visualizar com nitidez o conteúdo cativante na tela, mesmo sob luz solar directa.*`,
  },
  sec7: {
    titlea: `Tela de Toque  <br class='pc'/>Molhada`,
    desca: `Mãos molhadas`,
    titleb: `Desbloqueio por <br />Impressão Digital <br class='pc'/>na Tela`,
    descb: `Rápido e seguro`,
  },
  sec8: {
    titlea: `EXCELÊNCIA NA`,
    titleb: `ESTÉTICA`,
    desc: `Inspire-se na natureza mágica, com estética e processo avançados, transforme o S25 numa peça de moda! `,
  },
  sec9: {
    title: `Incrivelmente fino`,
    desc: `Apenas 185 g de peso e 7,3 mm de espessura*`,
  },
  sec10: {
    titlea: `Uma criação com estilo`,
    desca: `A moda de um lado, a tecnologia do outro. Combinando inspiração natural com conceitos de design de vanguarda, o Processo de Revestimento Óptico avançado cria duas texturas de deserto e menta, exalando um toque de qualidade superior.`,
    colora: `Brilho do Saara`,
    infoa: `Inspirado nas dunas douradas do deserto do Saara, é como uma magnífica cena do Saara a brilhar sob o sol.`,
    colorb: `Mint Mambo`,
    infob: `Inspirado no popular verde menta, fresco e vibrante, combinado com a elegância dos passos de dança do mambo, é exatamente como o estilo de vida dos jovens que seguem a moda e amam a vida.`,
    titleb: `Preto com um toque especial`,
    descb: `Design minimalista, preto intemporal, toque mate confortável, um clássico que nunca desaparece.`,
    colorc: `Preto Bromo`,
    infoc: `Inspirado no basalto do Monte Bromo, na Indonésia, reflecte o brilho único do basalto sob a luz do sol, fazendo lembrar as estrelas cintilantes do céu noturno.`,
  },
  sec11: {
    title: `Sincronize o seu estado de espírito`,
    desc: `Anel Luminoso LED`,
    info: `O Anel Luminoso LED não só fornece diferentes informações de estado através dos seus efeitos de iluminação, como também serve de complemento elegante aos smartphones, tornando-o visualmente apelativo e prático.`,
    f1: `Carregamento`,
    f2: `Jogos`,
    f3: `Notificações`,
  },
  sec12: {
    title: `Um companheiro <br />de confiança`,
    desc: `Com uma classificação IP54 para resistência ao pó e à água, este dispositivo está bem protegido contra o desgaste diário, incluindo a entrada de pó e salpicos ligeiros de água.`,
  },
  sec13: {
    titlea: `EXCELÊNCIA NO `,
    titleb: `DESEMPENHO`,
    desc: `A notável melhoria do desempenho, associada a uma optimização efectiva do software, uma experiência de "telefone novo" durante muitos anos.`,
  },
  sec14: {
    title: `60 meses de utilização sem problemas`,
    desc: `Após ter sido submetido a testes rigorosos no laboratório da itel, este telefone tem a garantia de não apresentar atrasos durante 5 anos. Graças à potente Tecnologia de Expansão da Memória Virtual e à Tecnologia de Armazenamento Atom, já não precisa de se preocupar com a diminuição do desempenho do telefone ao longo do tempo.`,
    f1a: `Até`,
    f1b: `16(8+8)GB RAM`,
    f1c: `18 Aplicações a funcionar em simultâneo.*`,
    f2a: `Até`,
    f2b: `128GB ROM`,
    f2c: `Capacidade para armazenar mais de 30.000 fotos*`,
  },
  sec15: {
    title: `Liberte a fera`,
    desc: `O S25 possui um potente processador octa-core com ARM Cortex-A75 até 2,2 Ghz, associado a um sistema de arrefecimento Graphite, para libertar totalmente o seu desempenho e permitir-lhe desfrutar facilmente dos principais jogos para telefone.`,
  },
  sec16: {
    title: `Super capacidade de <br class='mb'/> penetração em paredes`,
    desc: `O S25 suporta Super Wi-Fi, proporcionando uma latência ultra-baixa para jogos sem interrupções e mudando automaticamente para a melhor rede em diferentes redes Wi-Fi, oferecendo uma intensidade de sinal significativamente mais forte em espaços públicos com Wi-Fi partilhado.`,
    f1a: `6.5MB/s`,
    f1b: `Velocidade de descarregamento ao <br class='mb'/> utilizar Wi-Fi e Bluetooth em conjunto`,
    f2a: `26ms*`,
    f2b: `Latência super  <br class='mb'/> baixa para jogos`,
    f3a: `5x`,
    f3b: `Mudança mais rápida <br class='mb'/> para a rede Wi-Fi ideal`,
  },
  sec17: {
    titlea: `Toda a potência  <br class='mb'/> na sua mão`,
    desca: `O S25 vem com uma enorme bateria de 5000 mAh e um carregamento super rápido de 18 W`,
    titleb: `Sem comprometer os jogos`,
    descb: `Com a Tecnologia de Carregamento de Desvio, pode ignorar a bateria e alimentar o telefone directamente, garantindo uma experiência sem aquecimento enquanto joga jogos e carrega simultaneamente.*`,
  },
  sec18: {
    titlea: `EXCELÊNCIA NA`,
    titleb: `FOTOGRAFIA`,
    desc: `Câmaras frontal e traseira ultra nítidas,com características e filtros especialmente concebidos,transformando toda a gente num mestre da fotografia.`,
  },
  sec19: {
    f1a: `Câmera`,
    f1b: `32 MP AI para Selfies`,
    f1c: `FOV: 88.9° `,
    f1d: `·Abertura: f/2.2`,
    f2a: `50MP`,
    f2b: `Câmera Ultra-nítida`,
    f2c: `Tamanho do pixel: 0.64μm `,
    f2d: `·Abertura: f/1.6`,
  },
  sec20: {
    title: `A beleza em foco`,
    desc: `A Câmera 32 MP AI para Selfies com grande ângulo, que inclui Beleza AI 2.0, capta selfies impressionantes com detalhes e nitidez excepcionais, mesmo em fotos de grupo.`,
    tipsa: `Suporte para o Controlo`,
    tipsb: `por Voz do Obturador`,
    tipsc: `Suporte para o Obturador `,
    tipsd: `de Sorrisos`,
  },
  sec21: {
    title: `Clareza em todos os pormenores`,
    subTitlea: `Modo 50 MP`,
    infoa: `A Câmera Ultra Nítida de 50 MP, a melhor da sua classe, permite-lhe captar sem esforço fotos nítidas e cativantes em qualquer ambiente complexo, desde cenários com pouca luz a cenários com luz de fundo. Melhor ainda, pode captar os seus momentos mais marcantes gravando em vídeo 2K!`,
    subTitleb: `Modo Super Noturno`,
    off: `Desligado`,
    on: `Ligado`,
    hdr: `Super HDR`,
  },
  sec22: {
    title: `Capture com estilo`,
    desc: `Atreva-se a integrar a tecnologia AI nas fotografias móveis, criando três filtros de tons estilísticos distintos que permitem que as suas fotos transmitam sem esforço uma variedade de emoções e atmosferas. Juntamente com a utilização de uma marca de água principal exclusiva, cada fotografia que tira é instantaneamente transformada numa obra de arte.`,
    f1: `Padrão`,
    f2: `Brilho`,
    f3: `Mestre`,
  },
  sec23: {
    title: `Capture com diversão`,
    desc: `Abrace a diversão de Vlogging com Gravação de Vídeo de Dupla Visualização, captando sem esforço as suas reacções e a paisagem deslumbrante que está a apreciar, ou as interacções envolventes com os seus amigos.`,
  },
  sec24: {
    titlea: `EXCELÊNCIA NA`,
    titleb: `EXPERIÊNCIA`,
    desc: `Todas as caraterísticas são meticulosamente refinadas,com actualizações e optimizações contínuas, garantindo que é sempre fácil de utilizar.`,
  },
  sec25: {
    title: `O Novíssimo itel OS 14,5`,
    desc: `Baseado no mais recente Android 14, introduz um design de IU mais elegante e funcionalidades melhoradas de widgets de ambiente de trabalho, oferecendo-lhe uma experiência de sistema esteticamente mais agradável e sem falhas.`,
  },
  sec26: {
    android: {
      title: `Atualizável para  <br class='mb' /> Android 15™`,
      desc: `O suporte para 2 anos de actualizações do sistema Android e dos patches de segurança prolonga significativamente a vida útil do seu telefone.`,
    },
    gpt: {
      title: `Assistente de AI GPT`,
      desc: `Diga olá ao seu melhor assistente! Liberta as suas mãos e ajuda-o a realizar muitas tarefas simples.`,
    },
    aiCall: {
      title: `Cancelamento de Ruído <br class='pc'/>de Chamadas com AI`,
    },
    aiWallpaper: {
      title: `AI Wallpaper`,
    },
    askAi: {
      title: `ASK AI`,
    },
    dynamicBar: {
      title: `Dynamic Bar`,
      desc: `Bem-vindo à Dynamic Bar, onde aceder a notificações importantes, como o estado da bateria, chamadas recebidas, lembretes e estado de desbloqueio, é agora mais cómodo e simples do que nunca.`,
    },
    aod: {
      title: `AOD Inteligente`,
      desc: `As informações importantes <br class='mb'/> são facilmente acessíveis.`,
    },
    infrared: {
      title: `Controlo Remoto<br class='mb'/> por Infravermelhos`,
      desc: `Transforme o seu smartphone <br class='mb'/> num controlador <br class='pc'/> versátil <br class='mb'/> para electrodomésticos.*`,
    },
    nfc: {
      title: `NFC`,
      desc: `Não é necessário trazer uma carteira ou um cartão de transporte para sair.*`,
    },
    dts: {
      title: `Som Por DTS`,
      desc: `O áudio DTS proporciona um som envolvente e de alta fidelidade ao seu smartphone para uma experiência de audição melhorada.`,
    },
  },
  sec27: {
    title: `Conectividade  <br class='pc'/> inteligente`,
    desc: `Está integrado com a aplicação iPulse e suporta uma interligação perfeita com o seu relógio itel, permitindo-lhe controlar remotamente a fotografia do smartphone e sincronizar os dados de saúde com o telefone. Não se trata apenas da Internet das Coisas, representa um estilo de vida na moda.*`,
  },
  sec28: {
    notes: `Notas`,
    f1: `1. Os dados relativos à Fluência a 60 meses são obtidos a partir do Laboratório da itel. Os dados reais podem variar devido a factores como os ambientes de teste ou os métodos de cálculo, pelo que se deve consultar o produto real.`,
    f2: `2. A RAM da versão S25 128+16 GB é composta por (8+8) GB de expansão.`,
    f3: `3. Os dados relativos ao rácio tela/corpo e ao brilho foram obtidos no Laboratório da itel. Os dados reais podem variar devido a factores como os ambientes de teste ou os métodos de cálculo, pelo que se deve consultar o produto real.`,
    f4: `4. Os dados relativos ao peso e à espessura foram obtidos no Laboratório da itel. Os dados reais podem variar devido a factores como os ambientes de teste ou os métodos de cálculo, pelo que se deve consultar o produto real.`,
    f5: `5. Os dados de armazenamento de "mais de 30.000 Fotos" são obtidos a partir do Laboratório da itel. Os dados reais podem variar devido a factores como os ambientes de teste ou os métodos de cálculo, pelo que se deve consultar o produto real.`,
    f6: `6. Os dados das 18 Aplicações em Execução Simultânea foram obtidos no Laboratório da itel. Os dados reais podem variar devido a factores como os ambientes de teste ou os métodos de cálculo, pelo que se deve consultar o produto real.`,
    f7: `7. Os dados do Super Wi-Fi são obtidos a partir do Laboratório da itel. Os dados reais podem variar devido a factores como os ambientes de teste ou os métodos de cálculo, pelo que se deve consultar o produto real. `,
    f8: `8. A bateria do itel S25 tem uma capacidade típica de 5000 mAh e uma capacidade nominal de 4900 mAh.`,
    f9: `9. Os dados da Tecnologia de Carregamento de Desvio são obtidos a partir do Laboratório da itel. Os dados reais podem variar devido a factores como os ambientes de teste ou os métodos de cálculo, pelo que se deve consultar o produto real.`,
    // f10: `9. The data of Bypass Charging Tech is obtained from the itel Lab. Actual data <br class='mb'/> may vary due to factors such as test environments or calculation <br class='pc'/> methods, so <br class='mb'/> please refer to the actual product.`,
    f11: `10. Android é uma marca registada da Google LLC.`,
    f12: `11. A disponibilidade das funcionalidades de Controlo Remoto por Infravermelhos e NFC pode variar consoante a região e o dispositivo. Para mais detalhes, consultar a situação concreta.`,
    f13: `12. O iPulse, a aplicação de relógio própria da itel, é amplamente compatível e pré-instalada na Série S25 do itel.`,
    f14: `13. As imagens do produto são apenas para referência, consulte o produto real. Algumas especificações e descrições podem ser alteradas devido a substituições de fornecedores. Consulte o produto real. Os dados mencionados baseiam-se nas nossas especificações técnicas de design, laboratório e dados de teste do fornecedor, podendo as situações reais variar ligeiramente devido a diferentes versões de software de teste, ambientes de teste específicos e versões.`,
  },
  video: {
    sec23: {
      pc: {
        src: "/fileadmin/assets/v/S25/dist/videos/sec23Pc.mp4",
        post: "",
      },
      mob: {
        src: "/fileadmin/assets/v/S25/dist/videos/sec23Pc.mp4",
        post: "",
      },
    },
    sec2: {
      pc: {
        src: "/fileadmin/assets/v/S25/dist/videos/shortPc.mp4",
        post: "",
      },
      mob: {
        src: "/fileadmin/assets/v/S25/dist/videos/shortMb.mp4",
        post: "",
      },
    },
    fullVideo: {
      pc: {
        src: "/fileadmin/assets/v/S25/dist/videos/longPc.mp4",
        post: "",
      },
      mob: {
        src: "/fileadmin/assets/v/S25/dist/videos/longMb.mp4",
        post: "",
      },
    },
  },
}
